### DISCUSSION TITLE
Sync only Trakt to Plex

### DISCUSSION THREAD

**Discussion by jmcelreavey** [Taxel/PlexTraktSync#1005] [Q&A] [answered]
Is it possible to only do a 1-way sync? I'm not interested in updating my trakt collection just keeping track of what I've watched.

**Comment by stevietv** [comment, marked as answer]
Look at your config.yml and adjust it to sync what you want.

Example is found here
https://github.com/Taxel/PlexTraktSync/blob/main/plextraktsync/config.default.yml

**Reply by jmcelreavey** [reply]
Legend! Thanks!

**Reply by jmcelreavey** [reply]
🤔 Is it possible to process my watched on trakt to plex rather than the other way around? My plex collection is much bigger than my watched collection on Trakt, would be quicker to go that way.. Probably not possible though.

**Reply by stevietv** [reply]
the example config shows this:
```
sync:
  plex_to_trakt:
    collection: true
    ratings: true
    watched_status: true
  trakt_to_plex:
    liked_lists: true
    ratings: true
    watched_status: true
    watchlist: true
```

so just set `plex_to_trakt: watched_status: false` and `trakt_to_plex: watched_status: true`
