### DISCUSSION TITLE
configure to autoscan on start

### DISCUSSION THREAD

**Discussion by gmillerd** [Taxel/PlexTraktSync#1021] [Q&A] [answered]
Hello,

I would like to use this project to scan and monitor in two different containers, and use ofelia in another.
However I don't want to scan on startup, I just want to scan when ofelia says. 
In the end, this is essentially just like a normal crontab would be for the scan container and the monitor would run 

The following works great, with that one exception. I tried to have the container start with "info" and then have the container re-invoked with "sync", but it always just runs info.

I can do silly over engineered stuff like, docker stop plex-traktsync immediately after stopping, or have the config file with "excluded-libraries" have everything included, then after running a scan of nothing, swap the config with a config file that has "excluded-libraries" with the libraries removed.

Any suggestions would be very appreciated, thanks

```yml
services:

  plex-traktofelia:
    image: mcuadros/ofelia:latest
    container_name: plex-traktofelia
    command: daemon --docker
    restart: unless-stopped
    depends_on:
      - plex-traktsync
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.job-run.plextraktsync.schedule: "0 0 * * *"
      ofelia.job-run.plextraktsync.container: "plex-traktsync"
      ofelia.job-run.plextraktsync.command: "sync"

  plex-traktsync:
    image: ghcr.io/taxel/plextraktsync
    container_name: plex-traktsync
    restart: on-failure:2
    volumes:
      - /docker/plex/track/config:/app/config
    # command: info

  plex-traktwatch:
    image: ghcr.io/taxel/plextraktsync
    container_name: plex-traktwatch
    restart: unless-stopped
    volumes:
      - /docker/plex/track/config:/app/config
    command: watch
```

**Comment by simonc56** [comment]
- https://github.com/docker/compose/issues/1547
- https://github.com/docker/compose/issues/1896

**Comment by glensc** [comment, marked as answer]
override entry point to run sleep forever:

```yml
  plex-traktsync:
    image: ghcr.io/taxel/plextraktsync
    container_name: plex-traktsync
    restart: on-failure:2
    volumes:
      - /docker/plex/track/config:/app/config
   entrypoint: sleep
   command: infinity
```

you probably also need now to override back `ofelia.job-run.plextraktsync.entrypoint` to be `/init` (since 0.24.5)
