### DISCUSSION TITLE
Watchlist removed

### DISCUSSION THREAD

**Discussion by MrBamse** [Taxel/PlexTraktSync#1067] [General]
Hi, plextraktsync removed my entire Trakt Watchlist all of the sudden after many months with no issue and the config file explicitly states watchlist: false under trakt_to_plex but there was no such setting under the plex_to_trakt since i installed.

My plex token was invalid for a while and i just fixed it and ran a sync.
Has something changed?

**Comment by JourneyOver** [comment]
The same thing nearly happened to me, thankfully I was able to catch it before it deleted everything (it did remove a couple before I was able to shut it down though but thankfully it logs the ones it removes and I was able to re-add them)

You need to now add a `watchlist: false` under `plex_to_trakt` as well, otherwise anything in your trakt watchlist that is not in your plex watchlist will be removed on trakt.

so for sync it should now be like:
```
sync:
  plex_to_trakt:
    collection: true
    ratings: true
    watched_status: true
    watchlist: false
  trakt_to_plex:
    liked_lists: false
    ratings: true
    watched_status: true
    watchlist: true
    watchlist_as_playlist: false
```
changing true/false values to how ever you want them.

**Reply by rectifyer** [reply]
Dang, my watchlist was cleared since I didn't have this setting 😢

**Reply by JourneyOver** [reply]
> Dang, my watchlist was cleared since I didn't have this setting 😢

Yea they really fucked up when they released the watchlist stuff with having the watchlist set to `true` as default instead of `false` for plex to trakt, people who don't pay attention to update changelogs and just update things either themself or through automated methods or what have you have more than likely had their watchlist cleaned out due to this unless they caught it early like I did.

**Reply by glensc** [reply]
So, you figured it out, complaining it publicly in **their** discussions, but still not sending pull request for a proposal for a fix?

**Reply by glensc** [reply]
There's not even a feature request under issues if submitting a config change and documentation warning is too much for you:
- https://github.com/Taxel/PlexTraktSync/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

**Reply by JourneyOver** [reply]
and I was going to get to it eventually (opening a pr with the change) @glensc I've just been busy as fuck these past few weeks due to a death in the family on top of various other things that I haven't really had the time to do such things.

**Reply by glensc** [reply]
@JourneyOver sure, just no need to be aggressive towards the stuff you get for free borrowed from someone else's personal time. and sorry for your loss.

**Reply by JourneyOver** [reply]
@glensc Am I correct to assume that if a variable/value `ex: watchlist=true or false` doesn't exist in the users `config.yml` that it is instead pulled directly from the `config.default.yml`? (at least this is what I possibly gathered from looking at the code) so all that needs changed is the value in the `config.default.yml` from being `true` to being `false`?

**Reply by glensc** [reply]
@JourneyOver I'm sorry, I'm not familiar with the feature. I don't use it.

**Reply by glensc** [reply]
but yes, that's the config merge logic, all keys missing from user config are taken from default config.

and reading the discussion, I think you should also add a change to documentation (or default config itself?), i.e the warning for other users if they enable?

**Reply by JourneyOver** [reply]
something like
```
sync:
  plex_to_trakt:
    collection: true
    ratings: true
    watched_status: true
	watchlist: false # WARNING: if set to true without setting trakt_to_plex watchlist to true it will delete entries in your trakt watchlist that are not on your plex watchlist
  trakt_to_plex:
    liked_lists: false
    ratings: true
    watched_status: true
    watchlist: true
    watchlist_as_playlist: false
```

Though that might be too long, and would probably be better to be put into the readme file in the documentation for https://github.com/Taxel/PlexTraktSync#sync-settings instead.


Edit: anyways I'll look into doing this in a day or two when I have some time, unless someone else comes along and does it before me.
