### DISCUSSION TITLE
How to remove item from watchlist?

### DISCUSSION THREAD

**Discussion by D5120** [Taxel/PlexTraktSync#1205] [Q&A] [answered]
Hopefully a silly question, however I've tried various config settings, and unless I remove an item from Plex watchlist, and also manually remove from trakt.tv, it'll keep re-adding it.

I've searched through the discussions, and couldn't see an answer.

Example.

I've watched a Spawn in Plex, remove from watchlist, on the next sync, it's re-added.

Log entry

`2022-11-18T09:29:43.212769781Z INFO     Adding Spawn to Plex watchlist`

How I hoped it would work:

Watch Spawn, remove from watchlist, on next sync, Spawn is removed from trakt.tv watchlist.

I'm using PlexTraktSync [0.23.14] in a docker container.

This is my config

```
sync:
  plex_to_trakt:
    collection: false
    ratings: false
    watched_status: true
    watchlist: true
  trakt_to_plex:
    liked_lists: true
    ratings: false
    watched_status: true
    watchlist: true
    watchlist_as_playlist: false
```
I guess my question is, is PlexTraktSync designed to remove items, or only add during sync. It it's designed to remove, have I missed a config setting?
