### DISCUSSION TITLE
How to sync Trakt's watchlist to Plex's new unified watchlist?

### DISCUSSION THREAD

**Discussion by nanupnch** [Taxel/PlexTraktSync#1207] [Q&A] [answered]
### Confirmation

- [x] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [x] I have checked if identical issue already exists

### The problem

I am able to sync Trakt's watchlist to my personal server but, I want to be able to sync it to the new watchlist of Plex.

### Error trace / logs

```text

2022-11-21 22:07:45,352 INFO[PlexTraktSync]:PlexTraktSync [0.23.14]
2022-11-21 22:07:47,661 INFO[PlexTraktSync]:Completed full sync in 2.3 seconds

```

### Expected behavior

I want to be able to sync it to the new watchlist of Plex.

### Steps to reproduce the behavior

1. Run a sync with the provided config file.

### Workarounds

x

### Install method

pip

### Config file contents

[config.txt](https://github.com/Taxel/PlexTraktSync/files/10058573/config.txt)

### Version

0.23.14

### Python Version

3.10.4

### Operating System and Version

Windows 11 x64

**Comment by simonc56** [comment]
Read and edit your `config.yml` file to suit your need, then paste it here.
We'll check together what's not clear in it.

**Comment by nanupnch** [comment]
```yml
cache:
  path: $PTS_CACHE_DIR/trakt_cache

excluded-libraries:
  - Private
  - Family Holidays

config:
  dotenv_override: true

plex:
  timeout: 30

logging:
  append: true
  # Whether to show timestamps in console messages
  console_time: false
  debug: false
  filename: plextraktsync.log
  filter:
#    # Filter out all messages with level WARNING
#    - level: WARNING
#    # Filter out message with level WARNING and containing a text
#    - level: WARNING
#      message: "not found on Trakt"
#    - message: "because provider local has no external Id"
#    - message: "because provider none has no external Id"
#    - message: "Retry using search for specific Plex Episode"

# settings for 'sync' command (default)
sync:
  plex_to_trakt:
    collection: false
    ratings: false
    watched_status: false
    # If plex_to_trakt watchlist=false and trakt_to_plex watchlist=true
    # the Plex watchlist will be overwritten by Trakt watchlist
    watchlist: true
  trakt_to_plex:
    liked_lists: false
    ratings: false
    watched_status: false
    # If trakt_to_plex watchlist=false and plex_to_trakt watchlist=true
    # the Trakt watchlist will be overwritten by Plex watchlist
    watchlist: true
    # If you prefer to fetch trakt watchlist as a playlist instead of
    # plex watchlist, toggle this to true (is read only if watchlist=true)
    watchlist_as_playlist: false

# settings for 'watch' command
watch:
  add_collection: false
  remove_collection: false
  # what video watched percentage (0 to 100) triggers the watched status
  scrobble_threshold: 80
  # true to scrobble only what's watched by you, false for all your PMS users
  username_filter: true

xbmc-providers:
  movies: imdb
  shows: tvdb

# vim:ts=2:sw=2:et
```
