### DISCUSSION TITLE
Is it just me or PTS is trying to read through all my plex library even if I'm not exporting collection to trakt?

### DISCUSSION THREAD

**Discussion by mochasweet** [Taxel/PlexTraktSync#1305] [Q&A]
For the time being, I only intend to perform one-way sync of my watch history/progress and watchlist from plex to trakt. 
The following is my config.yml:

```yml
cache:
  path: $PTS_CACHE_DIR/trakt_cache

excluded-libraries:
  - Private
  - Family Holidays

config:
  dotenv_override: true

plex:
  timeout: 30

logging:
  append: true
  # Whether to show timestamps in console messages
  console_time: false
  debug: false
  filename: plextraktsync.log
  filter:

sync:
  plex_to_trakt:
    collection: false
    ratings: true
    watched_status: true
    watchlist: true
  trakt_to_plex:
    liked_lists: false
    ratings: false
    watched_status: false
    watchlist: false
    watchlist_as_playlist: false

watch:
  add_collection: false
  remove_collection: false
  scrobble_threshold: 90
  username_filter: true

xbmc-providers:
  movies: imdb
  shows: tvdb
```
However, this is what I keep getting from `docker logs -f plextraktsync` for sync command
![image](https://user-images.githubusercontent.com/117631806/209084873-74fbb57e-92d8-480a-af24-efc216a2d9cc.png)
The TV shows that appear in the logs are neither in my watchlist nor watched by me, how do I go about syncing history and watchlist only? I checked my trakt profile just  now, the history & progress syncing is complete, watchlist is still empty, how to get PlexTraktSync to sync my watchlist from my plex server to trakt? Thanks

**Comment by simonc56** [comment]
> The TV shows that appear in the logs

Appears saying what ? Show the logs.

> how to get PlexTraktSync to sync my watchlist from my plex server to trakt?

Like this :

```yaml
sync:
  plex_to_trakt:
    watchlist: true
```
