### DISCUSSION TITLE
Watched status is not getting synced from Trakt to Plex

### DISCUSSION THREAD

**Discussion by some-continuity** [Taxel/PlexTraktSync#1406] [Support]
Hi,
For some reason I can't get the watched status sync from Trakt into Plex to work.
I have setup a new Plex instance and added a movie to the library.
I then make sure that the Movie is unwatched in Plex, and watched in Trakt.
I then run the sync command, and it runs without any errors. However, the logs never
show that the movie has been set as watched inside Plex.
After it has finished running, the movie state is unwatched in Plex.
Now I thought that this might be an issue with the connection, so I did the reverse, 
and added a movie into Plex, set it as watched inside Plex, and unwatched inside Trakt.
This worked, and after running sync the movie was set as watched in Trakt.

Things I have tried:

- I tried deleting the `trakt_cache.sqlite`
- I made a new Trakt account and added the movie manually and set it as watched. This worked and the movie was set as watched inside Plex. However I can't transfer my Trakt history to this new account, so not a viable solution.
- Tried a clean Plex instance, this had no effect.

The only changes I made to the default config are:
```yaml
sync:
  plex_to_trakt:
    collection: false
    # Clear collected state of items not present in Plex
    clear_collected: false
    ratings: false
    watched_status: false
    # If plex_to_trakt watchlist=false and trakt_to_plex watchlist=true
    # the Plex watchlist will be overwritten by Trakt watchlist
    watchlist: false
  trakt_to_plex:
    liked_lists: false
    ratings: false
    watched_status: true
    # If trakt_to_plex watchlist=false and plex_to_trakt watchlist=true
    # the Trakt watchlist will be overwritten by Plex watchlist
    watchlist: false
    # If you prefer to fetch trakt watchlist as a playlist instead of
    # plex watchlist, toggle this to true (is read only if watchlist=true)
    watchlist_as_playlist: false
````
*I tried changing the plex_to_trakt watched_status to true but it did nothing.

I also turned on debugging, this is the log.
[plextraktsync.log](https://github.com/Taxel/PlexTraktSync/files/10679534/plextraktsync.log)

Has anyone had this issue, or any idea what is going wrong?
Thanks for the assistance.
