### DISCUSSION TITLE
Notification support

### DISCUSSION THREAD

**Discussion by mgrimace** [Taxel/PlexTraktSync#1971] [Ideas]
I'm new to using this script, and ideally [apprise ](https://github.com/caronc/apprise) or [ntfy ](https://github.com/binwiederhier/ntfy )support would be great - a quick message as to sync successful, what was synced, etc.

**Comment by mgrimace** [comment]
Specifically, using docker compose version, with scheduling on a headless home server. My use-case is to fully 'automate' the script now, and it'd be great to have a quick notification each run.

**Reply by simonc56** [reply]
For a quick and dirty check I run this :

```bash
exit_code=$(docker inspect plextraktsync --format='{{.State.ExitCode}}')
if [ $exit_code -ne 0 ] ; then
  curl -s -X POST https://api.telegram.org/bot$telegram_token/sendMessage -d chat_id=$telegram_chat_id -d text="$text"
fi
```

**Reply by mgrimace** [reply]
> For a quick and dirty check I run this :
> 
> ```shell
> exit_code=$(docker inspect plextraktsync --format='{{.State.ExitCode}}')
> if [ $exit_code -ne 0 ] ; then
>   curl -s -X POST https://api.telegram.org/bot$telegram_token/sendMessage -d chat_id=$telegram_chat_id -d text="$text"
> fi
> ```

Interesting, I could probably adapt this for NTFY vs. telegram… as a novice, where do I _put_ this snippet? I run the service using the linuxserver.io docker image:

```
services:

  plextraktsync:
    <<: *homelab-default
    image: lscr.io/linuxserver-labs/plextraktsync:latest
    container_name: plextraktsync
    volumes:
      - ${DOCKERDIR}/appdata/plextraktsync/config:/config
```
