### DISCUSSION TITLE
how to setting seperate the watchlist sync interval 10min except all other?

### DISCUSSION THREAD

**Discussion by ericvlog** [Taxel/PlexTraktSync#2086] [General]
``` 
 scheduler:
    image: mcuadros/ofelia:latest
    container_name: scheduler
    depends_on:
      - plextraktsync
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.job-run.plextraktsync.schedule: "@every 1h"
      ofelia.job-run.plextraktsync.container: "plextraktsync"
  plextraktsync:
    image: ghcr.io/taxel/plextraktsync:latest
    container_name: plextraktsync
    command: sync
    volumes:
      - ./plextraktsync/config:/app/config
  plextraktsyncwatch:
    image: ghcr.io/taxel/plextraktsync:latest
    container_name: plextraktsync-watch
    restart: unless-stopped
    command: watch
    volumes:
      - ./plextraktsync/config:/app/config
```

above  is my plextraktsync and it run well, how do i only sync watchlist more frequency let say 10 or 5 mins, and leave the above sync as normal. do I need add another plextraktsync? thanks
