### DISCUSSION TITLE
Unable to change the volume location

### DISCUSSION THREAD

**Discussion by tokendad** [Taxel/PlexTraktSync#2228] [Support]
Im trying to change the default config location.    Heres my compose:

```
  plextraktsync:
    image: ghcr.io/taxel/plextraktsync
    command: sync
    container_name: plextraktsync
    restart: unless-stopped
    volumes:
      - /data/DockerConfigs/plextraksync_data:/config 
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
```

When I created it ,  it defaulted to the docker location /var/lib/docker/volume location.   on Ubuntu 24.04

For reference here's my sonarr config that works correctly.

```
  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr
    ports:
      - "8989:8989"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/DockerConfigs/sonarr_data:/config # config files
      - /media:/media #  media folder
    restart: unless-stopped
```

directory permission

drwxrwxr-x  2 user group 4.0K Apr 13 13:34 plextraksync_data
