### DISCUSSION TITLE
[How-to] Install with Portainer (in Home Assistant OS)

### DISCUSSION THREAD

**Discussion by antonio1475** [Taxel/PlexTraktSync#831] [Show and tell]
I raised the question in [Discussion 827](https://github.com/Taxel/PlexTraktSync/discussions/827).
@twolaw pointed me in a direction, which surpassed my knowledge but made me try something else: Portainer in Home Assistant OS.

So here's a guide, which will be basic for many, but hopefully useful for other noobs.
It's very close (obviously) to the [Unraid setup](https://github.com/Taxel/PlexTraktSync#unraid-setup) Readme part, but adjusted for Portainer:

**First, install Portainer**
1. In HA, go to Configuration > Add-on Store > 3 dots top-right > Repositories
2. Add the repository that has an updated Portainer. I used alexbelgium's but I suppose there are others.
3. Search for Portainer. Install it. 
4. Read its documentetion. Disable Protection mode.
5. Start it, check logs.
6. Open Web UI

**Deploy PlexTraktSync image in Portainer**
1. Open Portainer
2. Left sidebar > Containers
3. Add container
4. Name: PlexTraktSync
5. Click Advanced Mode
6. Image: ghcr.io/taxel/plextraktsync:latest
![image](https://user-images.githubusercontent.com/63130724/156370706-535bfbbd-e9c1-4d86-bb8d-d709487661a6.png)
7. Scroll down. In Console, click on Interactive & TTY.
_This is different to the Readme file. I suppose writing -it in Command (Override) might work, but the commands seem to be different so I went' with Portainer's UI_
![image](https://user-images.githubusercontent.com/63130724/156370858-3d26918d-c820-4669-96d1-17eeee1ed17e.png)
8. **(Optional)**. If you want to run it in [watch mode](https://github.com/Taxel/PlexTraktSync#watch), go to Command & Logging > Command > Override > input watch (or 'watch', although it auto converts it)
![image](https://user-images.githubusercontent.com/63130724/156877327-428bdd76-1d93-4c0c-9dd7-fecf35e99ef6.png)
10. Scroll up: Deploy the container

**Run PlexTraktSync config**
1. In the list, go into the PlexTraktSync container
2. Start (if not already running)
3. Click on Console
4. Enable Use custom command
5. In Command, paste plextraktsync
![image](https://user-images.githubusercontent.com/63130724/156372785-545a1f57-46db-41d6-a97f-d36d2263fd68.png)
6. Go through the configuration in the console, filling the data as needed.
**Note: to paste (user, password, Trakt id, right click > paste! Ctrl-V doesn't work,
Also, don't use Ctrl-C to copy the Trakt code from the console, you'll terminate it. Right click, Copy**

**Run PlexTraktSync**
Issue: Portainer can't apparently schedule the job to start a container. So, 3 choices for you:

**_Option A: Run it on watch mode_** 
See step 8 above. If you didn't do it, you can Edit, do it, it will generate a new container and delete the older one. Setup (user, etc) seems to remain.

**_Option B: Manually start the container to sync_** 
Go to Portainer, Containers, find PlexTraktSync, Start it. It will sync (20 seconds, depending on your library) and stop it.
Repeat whenever you want.
It's a bit annoying having to find it every time, so...:

### Option C: AUTOMATE IT OR CREATE A BUTTON!
1. Go to Portainer, Containers, find PlexTraktSync, open it.
In configuration.yaml:
i. Add a sensor to [get the Portainer auth token](https://docs.portainer.io/v/ce-2.9/api/examples#authenticate-against-the-api-using-the-admin-account) every few hours instead of every time (expires after 8 hours). We extract the clean token by removing the first and last parts of it (it seems it's a consistent 176 characters).

2. Add a rest command that uses that extracted value in the Authorization header, to [start the container](https://docs.portainer.io/v/ce-2.9/api/examples#start-a-container)

_Obviously adapt to your addresses, ports, etc and parameters_

```
sensor:
  - platform: command_line
    command: 'curl -X POST -d "{\"Username\": \"myuser\",  \"Password\" : \"mypwd123\" }" http://192.168.0.27:9000/api/auth'
    name: "PortainerToken"
    scan_interval: 21600  # you can also make it much longer (a year: 31560000) and then include the service command_line Reload in the automation.
    value_template: "{{value[8:244]}}"  #remove first 8 characters and keep the next 236
    # value_template: "{{value[8:184]}}"  #remove first 8 characters and keep the next 176  # it seems Portainer has upgraded to 236 characther auth token instead of the previous 176 character. See above for updated line.

rest_command:
  plextraktsync:
    url: http://192.168.0.27:9000/api/endpoints/1/docker/containers/94PortainerPlexTraktSyncContainerIDbd8/start #HA URL & Portainer URL
    method: POST
    headers:
      Authorization: "{{states('sensor.portainertoken')}}"
```
The Container ID you can copy from Portainer > Containers > PlexTraktSync > Container ID

Use the rest command in an automation or button, it's a Service!
As mentioned, you can also first reload the command line token, wait a few seconds, and then execute the Rest command.

My automation:
```
alias: Sync Plex & Trakt
description: ''
trigger:
  - platform: time
    at: '06:00'
condition: []
action:
  - service: command_line.reload
    data: {}
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: rest_command.plextraktsync
    data: {}
mode: single
````

**Comment by antonio1475** [comment]
Scheduling / automation with Portainer in HA OS solved! See post edits at the end:
### Option C: AUTOMATE IT OR CREATE A BUTTON!

I feel dumb and smart at the same time (did it, but took so many hours). I hope it helps someone.

**Comment by antonio1475** [comment]
Edited the watch mode options and setup (step 8) thanks to @thedinz [from their post](https://github.com/Taxel/PlexTraktSync/discussions/834).

**Comment by jdecmac** [comment]
Un millón de gracias @antonio1475 !!! Está muy bien explicado y es la única forma que he encontrado de que me funcione al 100% plextraktsync. Pongo este comentario en español para que cualquier persona que le pase lo mismo que a mi y no encuentre información en español sobre plextraktsync pueda llegar aquí con una búsqueda. Thanks a lot!!!!

**Comment by glensc** [comment]
@antonio1475 shouldn't you send a PR to add this to readme as well? not copy everything but link to this thread, so this could be kept up to date by you.

**Comment by paterson37** [comment]
Is there a way I can set it so I can filter the user so it's only me on my server that gets synced? Is there a seperate config.yaml for this that I can put 

```
watch:
  username_filter: true
```

into?

**Comment by andcbii** [comment]
Is there anyway to start the container with out it kicking off a sync?

**Comment by smailpouri** [comment]
if this helps anyone:

Docker Desktop macOs Sonoma (Apple Silicon) via Portainer

Create a new stack:


```
services:
  scheduler:
    image: mcuadros/ofelia:latest
    container_name: ${PLEXTRAKTSYNC}_scheduler
    depends_on:
      - ${PLEXTRAKTSYNC}_sync
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.job-run.plextraktsync.schedule: "@every 6h"
      ofelia.job-run.plextraktsync.container: "${PLEXTRAKTSYNC}_sync"
  plextraktsync_sync:
    image: ghcr.io/taxel/plextraktsync:latest
    container_name: ${PLEXTRAKTSYNC}_sync
    #command: sync #uncomment After your first run, you need to go through the setup, the container stops without a config filled up. Check below using Terminal
    environment:
      - TZ=${TZ}
    volumes:
      - ${CONF_FOLDER}/${PLEXTRAKTSYNC}/config:/app/config
      - ${CONF_FOLDER}/${PLEXTRAKTSYNC}:/app/xdg

  plextraktsync_watch:
    image: ghcr.io/taxel/plextraktsync
    container_name: ${PLEXTRAKTSYNC}_watch
    hostname: ${PLEXTRAKTSYNC}_watch
    # command: watch #uncomment After your first run, you need to go through the setup, the container stops without a config filled up. Check below using Terminal
    restart: on-failure:2
    # privileged: true (no need)
    # stdin_open: true (no need)
    tty: true
    volumes:
      - ${CONF_FOLDER}/${PLEXTRAKTSYNC}/config:/app/config
      - ${CONF_FOLDER}/${PLEXTRAKTSYNC}:/app/xdg
    environment:
      - TZ=${TZ}
```
      
Add Variables through portainer GUI (at the bottom of the stack)
```
CONF_FOLDER=/path/to/macosFolder/Config
PLEXTRAKTSYNC=plextraktsync
TZ=America/Los_Angeles
```

First run setup:
Launch Terminal > 
`docker exec -it plextraktsync_watch /bin/ash`
or
`docker exec -it plextraktsync_sync /bin/ash` 
#Depending on which one you want to setup, no need to do both as they use the same config.

`plextraktsync login`

Follow the instructions until the end. 
At some point, it's not obvious but it shows you the list of servers, click an arrow down to select the one you want to use for the config.

Once you have gone through the process you are done.
I personally edited the `servers.yml` to add `- http://host.docker.internal:32400` at the top of the list.
```
servers:
  yourServerName: #autoretrieved by `plextraktsync login`
    token: 111111111 #autoretrieved by `plextraktsync login`
    urls:
    - http://host.docker.internal:32400
    - https://192-168-1-3:32400.111218763871687236871.plex.direct:32400
    - http://192.168.1.3:32400
    id: 1111111111 #autoretrieved by `plextraktsync login`
    config:
      libraries:
      - "Movies"
      - "TV Shows"
```
