### DISCUSSION TITLE
Docker-compose install permission error

### DISCUSSION THREAD

**Discussion by datbilling** [Taxel/PlexTraktSync#931] [Support] [answered]
I’m trying to install PlexTraktSync using the docker-compose method, but I’m getting a permission error shown in the screenshot when trying to run the container. Can anybody please help with this?

- Raspberry Pi 4
- Raspberry Pi OS
- Docker-compose version 1.21.0

docker-compose.yml
```
version: "3.0"
services:
  plextraktsync:
  image: ghcr.io/taxel/plextraktsync
  container_name: plextraktsync
  volumes:
    - ./config:/app/config
```

![98255D0C-DD36-470E-8D57-32C60ADD37A5](https://user-images.githubusercontent.com/58982799/172499193-cf1c6ea9-ebdc-4ca5-ae60-56169f2d7088.jpeg)
