### DISCUSSION TITLE
[Docker in Portainer]I finally figured out how to make this excellent script work by using docker

### DISCUSSION THREAD

**Discussion by TucoBruto** [Taxel/PlexTraktSync#963] [Show and tell]
You have to create a new container with interactive&TTY selected like this
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/20509862/177101950-2e58b8c9-2743-4e7c-b820-1c1255991fe3.png">

<img width="615" alt="image" src="https://user-images.githubusercontent.com/20509862/177101660-503b4f13-7260-40d0-91f0-55b98beab596.png">
and then mount a host dir for config files like this:
<img width="767" alt="image" src="https://user-images.githubusercontent.com/20509862/177101877-181e4160-86a5-4059-b25a-a4409f9a5bba.png">
then,deploy the container and get into the console page:
<img width="486" alt="image" src="https://user-images.githubusercontent.com/20509862/177102330-091c4ac5-7981-4fe7-a96f-9fb141942af2.png">

follow the Taxel's [setup guide](https://github.com/Taxel/PlexTraktSync#setup) to connect to your plex account,server,trakt
configure config.yml if you need.

**For automatic sync, just use this stack**
```yaml
services:
  scheduler:
    image: mcuadros/ofelia:latest
    container_name: scheduler
    depends_on:
      - plextraktsync
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.job-run.plextraktsync.schedule: "@every 2h"
      ofelia.job-run.plextraktsync.container: "plextraktsync"
```

**If watch mode enabled,the script won't sync watching status between plex and sync.**
SO,I just simply dupilcate the container that we created above,name it as plextraktsyncwatch.
and override the command option with 'watch' like this:
<img width="416" alt="image" src="https://user-images.githubusercontent.com/20509862/177106457-7a65ed00-5769-49cf-9220-9e19d83eaec7.png">

then deploy it.

bang! everything works fine now!

NOW,we have 3 containers working together,one for Syncing,one for Scrobbling,and one for Automatic routine.

hope this would help those who want to use docker but dont know how.

**Comment by hrenaud** [comment]
Here is my configuration after discovering this discussion. Thanks for the help it gave me :)

```yml
services:
  scheduler:
    image: mcuadros/ofelia:latest
    container_name: scheduler
    restart: "unless-stopped"
    depends_on:
      - plextraktsync
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.job-run.plextraktsync.schedule: "@every 2h"
      ofelia.job-run.plextraktsync.container: "plextraktsync"
  plextraktsync:
    image: ghcr.io/taxel/plextraktsync:latest
    container_name: plextraktsync
    restart: "unless-stopped"
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - /home/plextraktsync/plextraktsync/config:/app/config
  plextraktsyncwatch:
    image: ghcr.io/taxel/plextraktsync:latest
    container_name: plextraktsyncwatch
    restart: "unless-stopped"
    privileged: true
    stdin_open: true
    tty: true
    # command: watch
    volumes:
      - /home/plextraktsync/plextraktsyncwatch/config:/app/config
```

**Reply by glensc** [reply]
"watch" and "sync" can share the config dir, no need to duplicate. also for "plextraktsyncwatch" you have commented out "command: watch", so it really does "sync" as well. and "privileged: true" is not needed, probably "stdin_open" and "tty" can be dropped as well.

**Reply by hrenaud** [reply]
I have separated the configurations to have separate logs, maybe this is not necessary.

The command `watch` is commented because at installation, as nothing is configured, it makes the container crash. It's more like a reminder to do it later, after the configuration.

**Interactive** and **TTY** are set automatically because to configure plextraktsync you have to activate them.

My NAS asks to have privileged set to true, I don't know why 🤷‍♂️

**Comment by leni8ec** [comment]
## My steps:

1. Create stack in Portainer (by [manual](https://github.com/Taxel/PlexTraktSync#docker-compose)) → Deploy 
2. Open `plextraktsync` **container** (in this stack) settings → enable “`Interactive & TTY`” (no need to disable it anymore) → Deploy
3. Run and attach console (`/bin/ash`)
4. Run command in console `plextraktsync sync` (or `plextraktsync login`) - and follow [instructions](https://github.com/Taxel/PlexTraktSync#setup) to get credentials
5. Stop the container (if it was not stopped automatically after synchronization), the next time it will be automatically started by the scheduler

**Profit!**

___
#### Enabling Interactive & TTY
![image](https://github.com/Taxel/PlexTraktSync/assets/2379473/4f3caded-b17e-4c9b-9d52-136d4cc59798)

#### My Stack example
```
version: '2'
services:
  plextraktsync:
    image: ghcr.io/taxel/plextraktsync
    command: sync
    container_name: plextraktsync
    restart: on-failure:2
    volumes:
      - /home/user/docker/plextraktsync/config:/app/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
  # Shedule task
  scheduler:
    image: mcuadros/ofelia:latest
    container_name: plextraktsync-scheduler
    restart: unless-stopped
    depends_on:
      - plextraktsync
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=Europe/Moscow
    labels:
      ofelia.job-run.plextraktsync.schedule: "@every 6h"
      ofelia.job-run.plextraktsync.container: "plextraktsync"
```

**Reply by lpemcee21** [reply]
I get stuck on step 3. I must be missing something, when I try to connect, it stays on 'Connecting....' and never successfully completes for me to be able to proceed to step 4. Any ideas?

**Reply by bequbed** [reply]
Make sure you select /bin/ash from the container console.

**Comment by bequbed** [comment]
> You have to create a new container with interactive&TTY selected like this
> <img width="1138" alt="image" src="https://user-images.githubusercontent.com/20509862/177101950-2e58b8c9-2743-4e7c-b820-1c1255991fe3.png">
> 
> <img width="615" alt="image" src="https://user-images.githubusercontent.com/20509862/177101660-503b4f13-7260-40d0-91f0-55b98beab596.png">
> and then mount a host dir for config files like this:
> <img width="767" alt="image" src="https://user-images.githubusercontent.com/20509862/177101877-181e4160-86a5-4059-b25a-a4409f9a5bba.png">
> then,deploy the container and get into the console page:
> <img width="486" alt="image" src="https://user-images.githubusercontent.com/20509862/177102330-091c4ac5-7981-4fe7-a96f-9fb141942af2.png">
> 
> follow the Taxel's [setup guide](https://github.com/Taxel/PlexTraktSync#setup) to connect to your plex account,server,trakt
> configure config.yml if you need.
> 
> **For automatic sync, just use this stack**
> ```yaml
> services:
>   scheduler:
>     image: mcuadros/ofelia:latest
>     container_name: scheduler
>     depends_on:
>       - plextraktsync
>     command: daemon --docker
>     volumes:
>       - /var/run/docker.sock:/var/run/docker.sock:ro
>     labels:
>       ofelia.job-run.plextraktsync.schedule: "@every 2h"
>       ofelia.job-run.plextraktsync.container: "plextraktsync"
> ```
> 
> **If watch mode enabled,the script won't sync watching status between plex and sync.**
> SO,I just simply dupilcate the container that we created above,name it as plextraktsyncwatch.
> and override the command option with 'watch' like this:
> <img width="416" alt="image" src="https://user-images.githubusercontent.com/20509862/177106457-7a65ed00-5769-49cf-9220-9e19d83eaec7.png">
> 
> then deploy it.
> 
> bang! everything works fine now!
> 
> NOW,we have 3 containers working together,one for Syncing,one for Scrobbling,and one for Automatic routine.
> 
> hope this would help those who want to use docker but dont know how.

I followed this method but instead of 3 containers I have 2. One for sync and one for watch. Sync incorporates the scheduler to run every 30 minutes. 

However now I'm getting to two scroobles for everything I watch.

Any idea why?

**Reply by markbharris** [reply]
Is there a way to do this via CE edition of portainer?

**Comment by greg4168** [comment]
Attempting to setup watch today to scrobble as I watch stuff.  Following the info above but my watch container fails with this in the log:

```
ERROR    HTTPConnectionPool(host='localhost', port=32400): Max retries exceeded 
         with url: / (Caused by                                                 
         NewConnectionError('<urllib3.connection.HTTPConnection object at       
         0x7f6fb7d56f90>: Failed to establish a new connection: [Errno 111]     
         Connection refused'))    
```

Sync works as I get updates in Trakt within 2 hours.

Also, I only want to scrobble my Guest user, since that's what I use to watch.  Any way to do that?

Thanks in advance.  Here's my stack:

```yml
version: '2'
services:
  plextraktsync:
    image: ghcr.io/taxel/plextraktsync:latest
    command: sync
    container_name: plextraktsync
    restart: on-failure:2
    environment:
      - TZ=America/New_York
    volumes:
      - /var/lib/docker/volumes/plextraktsync/config:/config

  scheduler:
    image: mcuadros/ofelia:latest
    container_name: plextraktsync-scheduler
    restart: unless-stopped
    depends_on:
      - plextraktsync
    command: daemon --docker
    environment:
      - TZ=Americas/New_York
    volumes:
      - /var/lib/docker/volumes/plextraktsync/config:/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.job-run.plextraktsync.schedule: "@every 2h"
      ofelia.job-run.plextraktsync.container: "plextraktsync"

  plextraktsyncwatch:
    image: ghcr.io/taxel/plextraktsync:latest
    container_name: plextraktsync-watch
    restart: unless-stopped
    privileged: true
    stdin_open: true
    tty: true
    command: watch
    environment:
      - TZ=America/New_York
    volumes:
       - /var/lib/docker/volumes/plextraktsync/config:/config
       
```
