### DISCUSSION TITLE
Docker-Compose example of both Sync and Watch running under same service?

### DISCUSSION THREAD

**Discussion by xInsertx** [Taxel/PlexTraktSync#979] [Q&A]
Hi,

I was wondering if anyone could provide an example of 2 separate containers running under the same docker-compose for the sync and scrobble tasks respectively.

The idea would be to interactively set-up the credentials / etc then share the same volume/bind-mount. I am able to get one or the other running - but not both at the same time.

The intent was to replace the old plex-style plugin functionality.

edit: can someone also confirm what location/path the auth info gets saved? doesn't seem to be in the config dir (useless it's in the sqlite db?)

**Comment by glensc** [comment]
and then why don't you share **your** attempt?

**Comment by xInsertx** [comment]
@glensc Sorry for the late reply - just been busy. I ran the following compose to generate the containers - then "docker run interactive " the sync container to get it set-up.  I plan to fiddle with this more over the weekend.

I found the json files with the tokens etc after /bin/sh into the container. Is there a current 'recommend' on if 2 processes are running (assuming same user) should we read-only the mount or specific file on the 'watch' container?

Note: No scheduler is included because post testing ill let kube-scheduler worry about it (I prefer to test on stand-alone docker before importing to kube)

My intent is to get a template so I can pipe things to a script (until/if multi-user support is added) to build for additional users.

As a separate quick question - is there anything stopping me from generating the .json outside and mounting it (if I had the info already and want to map additional users) or would this be better suited via passing environmental variables?

```
services:
  sync:
    image: ghcr.io/taxel/plextraktsync:latest
    container_name: plexts-sync
    volumes:
      - /path/to/bind/config:/app/config
  watcher:
    image: ghcr.io/taxel/plextraktsync:latest
    container_name: plexts-watcher
    volumes:
      - /path/to/bind/config:/app/config
    command: watch
```
