### DISCUSSION TITLE
Multi-User docker-compose

### DISCUSSION THREAD

**Discussion by Anon0511** [Taxel/PlexTraktSync#997] [Show and tell]
Here is a docker-compose for syncing multiple users, thus running multiple instances, in my case 21 users. I just trashed it together and don't guarantee it to be best practice. Maybe you want to provide it as an example docker-compose.yml in the Git Repo?

Have a nice day!

```
version: '3.7'
services:
  plextraktsync: &default
    image: ghcr.io/taxel/plextraktsync
    container_name: plextraktsync
    restart: on-failure:2
    volumes:
      - /home/plextraktsync:/app/config
    networks:
      - plex

  plextraktsync1:
    <<: *default
    container_name: plextraktsync1
    volumes:
      - /home/plextraktsync1:/app/config

  plextraktsync2:
    <<: *default
    container_name: plextraktsync2
    volumes:
      - /home/plextraktsync2:/app/config

  plextraktsync3:
    <<: *default
    container_name: plextraktsync3
    volumes:
      - /home/plextraktsync3:/app/config

  plextraktsync4:
    <<: *default
    container_name: plextraktsync4
    volumes:
      - /home/plextraktsync4:/app/config

  plextraktsync5:
    <<: *default
    container_name: plextraktsync5
    volumes:
      - /home/plextraktsync5:/app/config

  plextraktsync6:
    <<: *default
    container_name: plextraktsync6
    volumes:
      - /home/plextraktsync6:/app/config

  plextraktsync7:
    <<: *default
    container_name: plextraktsync7
    volumes:
      - /home/plextraktsync7:/app/config

  plextraktsync8:
    <<: *default
    container_name: plextraktsync8
    volumes:
      - /home/plextraktsync8:/app/config

  plextraktsync9:
    <<: *default
    container_name: plextraktsync9
    volumes:
      - /home/plextraktsync9:/app/config

  plextraktsync10:
    <<: *default
    container_name: plextraktsync10
    volumes:
      - /home/plextraktsync10:/app/config

  plextraktsync11:
    <<: *default
    container_name: plextraktsync11
    volumes:
      - /home/plextraktsync11:/app/config

  plextraktsync12:
    <<: *default
    container_name: plextraktsync12
    volumes:
      - /home/plextraktsync12:/app/config

  plextraktsync13:
    <<: *default
    container_name: plextraktsync13
    volumes:
      - /home/plextraktsync13:/app/config

  plextraktsync14:
    <<: *default
    container_name: plextraktsync14
    volumes:
      - /home/plextraktsync14:/app/config

  plextraktsync15:
    <<: *default
    container_name: plextraktsync15
    volumes:
      - /home/plextraktsync15:/app/config

  plextraktsync16:
    <<: *default
    container_name: plextraktsync16
    volumes:
      - /home/plextraktsync16:/app/config

  plextraktsync17:
    <<: *default
    container_name: plextraktsync17
    volumes:
      - /home/plextraktsync17:/app/confi0g

  plextraktsync18:
    <<: *default
    container_name: plextraktsync18
    volumes:
      - /home/plextraktsync18:/app/config

  plextraktsync19:
    <<: *default
    container_name: plextraktsync19
    volumes:
      - /home/plextraktsync19:/app/config

  plextraktsync20:
    <<: *default
    container_name: plextraktsync20
    volumes:
      - /home/plextraktsync20:/app/config

  scheduler: &default1
    image: mcuadros/ofelia:latest
    container_name: scheduler
    depends_on:
      - plextraktsync
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.job-run.plextraktsync.schedule: "@every 6h"
      ofelia.job-run.plextraktsync.container: "plextraktsync"

  scheduler1:
    <<: *default1
    container_name: scheduler1
    depends_on:
      - plextraktsync1
    labels:
      ofelia.job-run.plextraktsync.container: "plextraktsync1"

  scheduler2:
    <<: *default1
    container_name: scheduler2
    depends_on:
      - plextraktsync2
    labels:
      ofelia.job-run.plextraktsync.container: "plextraktsync2"

  scheduler3:
    <<: *default1
    container_name: scheduler3
    depends_on:
      - plextraktsync3
    labels:
      ofelia.job-run.plextraktsync.container: "plextraktsync3"

  scheduler4:
    <<: *default1
    container_name: scheduler4
    depends_on:
      - plextraktsync4
    labels:
      ofelia.job-run.plextraktsync.container: "plextraktsync4"

  scheduler5:
    <<: *default1
    container_name: scheduler5
    depends_on:
      - plextraktsync5
    labels:
      ofelia.job-run.plextraktsync.container: "plextraktsync5"

  scheduler6:
    <<: *default1
    container_name: scheduler6
    depends_on:
      - plextraktsync6
    labels:
      ofelia.job-run.plextraktsync.container: "plextraktsync6"

  scheduler7:
    <<: *default1
    container_name: scheduler7
    depends_on:
      - plextraktsync7
    labels:
      ofelia.job-run.plextraktsync.container: "plextraktsync7"

  scheduler8:
    <<: *default1
    container_name: scheduler8
    depends_on:
      - plextraktsync8
    labels:
      ofelia.job-run.plextraktsync.container: "plextraktsync8"

  scheduler9:
    <<: *default1
    container_name: scheduler9
    depends_on:
      - plextraktsync9
    labels:
      ofelia.job-run.plextraktsync.container: "plextraktsync9"

  scheduler10:
    <<: *default1
    container_name: scheduler10
    depends_on:
      - plextraktsync10
    labels:
      ofelia.job-run.plextraktsync.container: "plextraktsync10"

  scheduler11:
    <<: *default1
    container_name: scheduler11
    depends_on:
      - plextraktsync11
    labels:
      ofelia.job-run.plextraktsync.container: "plextraktsync11"

  scheduler12:
    <<: *default1
    container_name: scheduler12
    depends_on:
      - plextraktsync12
    labels:
      ofelia.job-run.plextraktsync.container: "plextraktsync12"

  scheduler13:
    <<: *default1
    container_name: scheduler13
    depends_on:
      - plextraktsync13
    labels:
      ofelia.job-run.plextraktsync.container: "plextraktsync13"

  scheduler14:
    <<: *default1
    container_name: scheduler14
    depends_on:
      - plextraktsync14
    labels:
      ofelia.job-run.plextraktsync.container: "plextraktsync14"

  scheduler15:
    <<: *default1
    container_name: scheduler15
    depends_on:
      - plextraktsync15
    labels:
      ofelia.job-run.plextraktsync.container: "plextraktsync15"

  scheduler16:
    <<: *default1
    container_name: scheduler16
    depends_on:
      - plextraktsync16
    labels:
      ofelia.job-run.plextraktsync.container: "plextraktsync16"

  scheduler17:
    <<: *default1
    container_name: scheduler17
    depends_on:
      - plextraktsync17
    labels:
      ofelia.job-run.plextraktsync.container: "plextraktsync17"

  scheduler18:
    <<: *default1
    container_name: scheduler18
    depends_on:
      - plextraktsync18
    labels:
      ofelia.job-run.plextraktsync.container: "plextraktsync18"

  scheduler19:
    <<: *default1
    container_name: scheduler19
    depends_on:
      - plextraktsync19
    labels:
      ofelia.job-run.plextraktsync.container: "plextraktsync19"

  scheduler20:
    <<: *default1
    container_name: scheduler20
    depends_on:
      - plextraktsync20
    labels:
      ofelia.job-run.plextraktsync.container: "plextraktsync20"

networks:
  plex:
    external: true
```
