### ISSUE TITLE
pipx permission denied

### ISSUE THREAD

**Issue by G4Zz0L1** [Taxel/PlexTraktSync#1223]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists

### The problem

I've updated my docker-compose like I always do, but the plextraktsync container keeps restarting, showing the error below in the docker-compose logs.
This is my container config, I just use the watch function, and it has worked fine until now.

```yml
plextraktsync:
      image: ghcr.io/taxel/plextraktsync:latest
      container_name: plextraktsync
      restart: unless-stopped
      network_mode: host
      user: "1000:100"
      volumes:
         - ./PlexTraktSync/config:/app/config
      command: watch
      environment:
         - PGID=1000
         - PUID=100
         - TZ=Europe/Rome
```

### Error trace / logs

```text
plextraktsync  | Traceback (most recent call last):
plextraktsync  |   File "<frozen runpy>", line 198, in _run_module_as_main
plextraktsync  |   File "<frozen runpy>", line 88, in _run_code
plextraktsync  |   File "/app/plextraktsync/__main__.py", line 16, in <module>
plextraktsync  |     from plextraktsync.cli import cli
plextraktsync  |   File "/app/plextraktsync/cli.py", line 317, in <module>
plextraktsync  |     if enable_self_update():
plextraktsync  |        ^^^^^^^^^^^^^^^^^^^^
plextraktsync  |   File "/app/plextraktsync/commands/self_update.py", line 11, in enable_self_update
plextraktsync  |     package = pipx_installed(program_name())
plextraktsync  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
plextraktsync  |   File "/app/plextraktsync/util/packaging.py", line 41, in pipx_installed
plextraktsync  |     output = execx("pipx list --json")
plextraktsync  |              ^^^^^^^^^^^^^^^^^^^^^^^^^
plextraktsync  |   File "/app/plextraktsync/util/execx.py", line 9, in execx
plextraktsync  |     process = subprocess.Popen(
plextraktsync  |               ^^^^^^^^^^^^^^^^^
plextraktsync  |   File "/usr/local/lib/python3.11/subprocess.py", line 1022, in __init__
plextraktsync  |     self._execute_child(args, executable, preexec_fn, close_fds,
plextraktsync  |   File "/usr/local/lib/python3.11/subprocess.py", line 1899, in _execute_child
plextraktsync  |     raise child_exception_type(errno_num, err_msg, err_filename)
plextraktsync  | PermissionError: [Errno 13] Permission denied: 'pipx'
```

### Expected behavior

I'll expect the program to run like always

### Steps to reproduce the behavior

1. use the config above in an empty docker-compose.yml file
2. do `docker-compose up -d`
3. do `docker-compose logs -f`

### Install method

docker-compose

### Config file contents

```yaml
cache:
  path: $PTS_CACHE_DIR/trakt_cache
plex:
  timeout: 30
logging:
  append: true
  console_time: true
  debug: false
  filename: plextraktsync.log
sync:
  plex_to_trakt:
    collection: false
    ratings: false
    watched_status: true
    watchlist: false
  trakt_to_plex:
    liked_lists: false
    ratings: false
    watched_status: true
    watchlist: false
    watchlist_as_playlist: false
watch:
  add_collection: false
  remove_collection: false
  scrobble_threshold: 80
  username_filter: true
xbmc-providers:
  movies: tmdb
  shows: tvdb
```

### Version

:latest on the docker-compose, so the packaged one

### Python Version

the version inside the docker image

### Operating System and Version

Arch Linux

**Comment by glensc** [comment]
> Workarounds
>
> No response

you can always downgrade!

> Version
> `:latest` on the docker-compose, so the packaged one

don't cheat. say out the version!

**Comment by glensc** [comment]
there's no `pipx` installed in official docker image:

```
➜ docker run --entrypoint sh --rm -it ghcr.io/taxel/plextraktsync:0.24.1
/app # which pipx
/app # plextraktsync --version
PlexTraktSync 0.24.1
```

and why would you get permission error? docker runs with some selinux or AppArmor?

**Comment by G4Zz0L1** [comment]
I honestly couldn't tell, if I go with `docker run` it works like yours above, but if I use `docker-compose run` leaving the rest, it gives the error like before.
Docker it's installed like every other program here on Arch, from the repo, without any particular restriction (like selinux or apparmor).
I've also cleared all the plextraktsync images, redownloaded, and same thing happens.

```
❯ docker run --entrypoint sh --rm -it ghcr.io/taxel/plextraktsync:latest
/app # plextraktsync --version
PlexTraktSync 0.24.1
/app # exit
❯ docker-compose run --entrypoint sh --rm -it plextraktsync
/app $ plextraktsync --version
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/plextraktsync/__main__.py", line 16, in <module>
    from plextraktsync.cli import cli
  File "/app/plextraktsync/cli.py", line 317, in <module>
    if enable_self_update():
       ^^^^^^^^^^^^^^^^^^^^
  File "/app/plextraktsync/commands/self_update.py", line 11, in enable_self_update
    package = pipx_installed(program_name())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plextraktsync/util/packaging.py", line 41, in pipx_installed
    output = execx("pipx list --json")
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plextraktsync/util/execx.py", line 9, in execx
    process = subprocess.Popen(
              ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 1022, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.11/subprocess.py", line 1899, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'pipx'
/app $ 
```

**Comment by glensc** [comment]
you don't happen to have `docker-composer.override.yml` adding extra "volumes"?

and what about downgrading? since what version the problem starts?

**Comment by glensc** [comment]
share `docker-compose config` output, it should print all merged config

**Comment by glensc** [comment]
btw, unrelated to your problem, but these have no effect:

```yml
      environment:
         - PGID=1000
         - PUID=100
```

**Comment by G4Zz0L1** [comment]
No extra docker-compose.override, or anything fancy, just the config posted above.
Removing only other containers, the `docker-compose config` output:

```
❯ docker-compose config
name: docker-services
services:
[...]
  plextraktsync:
    command:
    - watch
    container_name: plextraktsync
    environment:
      PGID: "1000"
      PUID: "100"
      TZ: Europe/Rome
    image: ghcr.io/taxel/plextraktsync:latest
    network_mode: host
    restart: unless-stopped
    user: 1000:100
    volumes:
    - type: bind
      source: ./PlexTraktSync/config
      target: /app/config
      bind:
        create_host_path: true
[...]
networks:
  default:
    name: docker-services_default
```

> btw, unrelated to your problem, but these have no effect:
> 
> ```yaml
>       environment:
>          - PGID=1000
>          - PUID=100
> ```

Good to know, I'll remove them, and leave only the `user` key, thanks.
