### ISSUE TITLE
not marked as watched on trakt.tv

### ISSUE THREAD

**Issue by floppy86** [Taxel/PlexTraktSync#1255]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists
- [X] I have tried downgrading to find version that can be used as a workaround

### The problem

the episode is marked as watched by plextraktsync inspect 10403

![image](https://user-images.githubusercontent.com/113219140/205445820-f7956f1c-f3e0-49ec-8114-034e9f0d7de6.png)

### Expected behavior

episode is marked as played on trakt.tv as well

### Steps to reproduce the behavior

1. have PlexTraktSync [0.24.6]
2. watch an episode of something
3. run plextracktsync
4. run plextraktsync inspect episode_just_watched

### Inspect of problematic items

```text
Inspecting 10403: <tmdb:3942849:Episode:10403:The-Peripheral-s01e08>
URL: https://app.plex.tv/desktop/#!/server/obfuscated/details?key=/library/metadata/10403
Title: The Creation of a Thousand Forests
Media.Duration: 00:57:35
Media.Type: 'episode'
Media.Guid: 'plex://episode/631a444b8f398183d86cf4fe'
Media.Guids: [<Guid:imdb://tt15801378>, <Guid:tmdb://3942849>, <Guid:tvdb://9342112>]
Audio: '5.1(side)', 'English (EAC3 5.1)'
Video: 'h264'
Subtitles:
  Subtitle 1: (English) Forced (codec: srt, selected: False, transient: None)
  Subtitle 2: (English) None (codec: srt, selected: False, transient: None)
  Subtitle 3: (English) SDH (codec: srt, selected: False, transient: None)
  Subtitle 4: (العربية) None (codec: srt, selected: False, transient: None)
  Subtitle 5: (català) None (codec: srt, selected: False, transient: None)
  Subtitle 6: (Čeština) None (codec: srt, selected: False, transient: None)
  Subtitle 7: (Dansk) None (codec: srt, selected: False, transient: None)
  Subtitle 8: (Deutsch) None (codec: srt, selected: False, transient: None)
  Subtitle 9: (Ελληνικά) None (codec: srt, selected: False, transient: None)
  Subtitle 10: (Español) Spanish (Latin America) (codec: srt, selected: False, transient: None)
  Subtitle 11: (Español) Spanish (Spain) (codec: srt, selected: False, transient: None)
  Subtitle 12: (euskara) None (codec: srt, selected: False, transient: None)
  Subtitle 13: (Suomi) None (codec: srt, selected: False, transient: None)
  Subtitle 14: (Filipino) None (codec: srt, selected: False, transient: None)
  Subtitle 15: (Français) French (Canada) (codec: srt, selected: False, transient: None)
  Subtitle 16: (Français) French (France) (codec: srt, selected: False, transient: None)
  Subtitle 17: (galego) None (codec: srt, selected: False, transient: None)
  Subtitle 18: (עברית) None (codec: srt, selected: False, transient: None)
  Subtitle 19: (हिन्दी) None (codec: srt, selected: False, transient: None)
  Subtitle 20: (magyar) None (codec: srt, selected: False, transient: None)
  Subtitle 21: (Indonesia) None (codec: srt, selected: False, transient: None)
  Subtitle 22: (Italiano) None (codec: srt, selected: False, transient: None)
  Subtitle 23: (日本語) None (codec: srt, selected: False, transient: None)
  Subtitle 24: (ಕನ್ನಡ) None (codec: srt, selected: False, transient: None)
  Subtitle 25: (한국어) None (codec: srt, selected: False, transient: None)
  Subtitle 26: (മലയാളം) None (codec: srt, selected: False, transient: None)
  Subtitle 27: (Melayu) None (codec: srt, selected: False, transient: None)
  Subtitle 28: (norsk bokmål) None (codec: srt, selected: False, transient: None)
  Subtitle 29: (Nederlands) None (codec: srt, selected: False, transient: None)
  Subtitle 30: (polski) None (codec: srt, selected: False, transient: None)
  Subtitle 31: (Português) Portuguese (Brazil) (codec: srt, selected: False, transient: None)
  Subtitle 32: (Português) Portuguese (Portugal) (codec: srt, selected: False, transient: None)
  Subtitle 33: (română) None (codec: srt, selected: True, transient: None)
  Subtitle 34: (Русский) None (codec: srt, selected: False, transient: None)
  Subtitle 35: (Svenska) None (codec: srt, selected: False, transient: None)
  Subtitle 36: (தமிழ்) None (codec: srt, selected: False, transient: None)
  Subtitle 37: (తెలుగు) None (codec: srt, selected: False, transient: None)
  Subtitle 38: (ไทย) None (codec: srt, selected: False, transient: None)
  Subtitle 39: (Türkçe) None (codec: srt, selected: False, transient: None)
  Subtitle 40: (Українська) None (codec: srt, selected: False, transient: None)
  Subtitle 41: (Tiếng Việt) None (codec: srt, selected: False, transient: None)
  Subtitle 42: (中文) Chinese (Simplified) (codec: srt, selected: False, transient: None)
  Subtitle 43: (中文) Chinese (Traditional) (codec: srt, selected: False, transient: None)
Parts:
  Part 1: D:\Sonarr\The Peripheral\Season 1\The Peripheral S01E08 The Creation of a Thousand Forests 1080p AMZN WEB-DL DDP5 1 H 264-NTb[TGx].mkv
Guids:
  Guid: <PlexGuid:tmdb://3942849>, Id: 3942849, Provider: 'tmdb'
  Guid: <PlexGuid:tvdb://9342112>, Id: 9342112, Provider: 'tvdb'
  Guid: <PlexGuid:imdb://tt15801378>, Id: tt15801378, Provider: 'imdb'
Metadata: {'collected_at': '2022-12-02:T04:40:38.000Z', 'media_type': 'digital', 'resolution': 'hd_1080p', 'audio': 'dolby_digital_plus', 'audio_channels': '5.1'}
Trakt: https://trakt.tv/episodes/6683800
Plex Rating: None
Trakt Rating: None
Watched on Plex: True
Watched on Trakt: True
Collected on Trakt: True
Plex play history:
- 2022-12-03 10:47:21 <Episode:10403:The-Peripheral-s01e08>: by obfuscated on Chromecast Google TV with Android
```

### Install method

pipx

### Config file contents

```yaml
cache:
  path: /root/.cache/PlexTraktSync/trakt_cache
config:
  dotenv_override: true
excluded-libraries:
- Private
- Family Holidays
logging:
  append: true
  console_time: false
  debug: false
  filename: plextraktsync.log
  filter: null
plex:
  timeout: 30
sync:
  plex_to_trakt:
    collection: true
    ratings: true
    watched_status: true
    watchlist: true
  trakt_to_plex:
    liked_lists: true
    ratings: true
    watched_status: true
    watchlist: true
    watchlist_as_playlist: false
watch:
  add_collection: false
  remove_collection: false
  scrobble_threshold: 80
  username_filter: true
xbmc-providers:
  movies: imdb
  shows: tvdb
```

### Version

0.24.6

### Python Version

3.10.6

### Operating System and Version

Linux-5.19.17-1-pve-x86_64-with-glibc2.35
