### ISSUE TITLE
cannot login to trakt

### ISSUE THREAD

**Issue by damonbreeden** [Taxel/PlexTraktSync#1290]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists
- [X] I have tried downgrading to find version that can be used as a workaround

### The problem

get this error when setting up `plextraktsync`
```
Log in to Trakt failed: Expecting value: line 1 column 1 (char 0), Try again.
```

### Error trace / logs

```text
Please enter your client id: xxx
Please enter your client secret: xxx
Attempting to authenticate with Trakt
Log in to Trakt failed: Expecting value: line 1 column 1 (char 0), Try again.
```

### Expected behavior

login successful

### Steps to reproduce the behavior

run `plextraktsync` and go through initial setup

### Install method

pip (not supported)

### Config file contents

```yaml
damon@hp-9470m:/mnt/drive1/backup$ plextraktsync config
# Config File: /home/damon/.local/lib/python3.8/site-packages/config.yml
cache:
  path: /home/damon/.local/lib/python3.8/site-packages/trakt_cache
excluded-libraries:
- Private
- Family Holidays
config:
  dotenv_override: true
plex:
  timeout: 30
logging:
  append: true
  console_time: false
  debug: false
  filename: plextraktsync.log
  filter: null
sync:
  plex_to_trakt:
    collection: true
    ratings: true
    watched_status: true
    watchlist: true
  trakt_to_plex:
    liked_lists: true
    ratings: true
    watched_status: true
    watchlist: true
    watchlist_as_playlist: false
watch:
  add_collection: false
  remove_collection: false
  scrobble_threshold: 80
  username_filter: true
xbmc-providers:
  movies: imdb
  shows: tvdb

# HTTP Cache
http_cache:
  policy:
    '*.trakt.tv/shows/*/seasons': 0
    '*.trakt.tv/sync/collection/shows': 0
    '*.trakt.tv/sync/watched/shows': 0
    '*.trakt.tv/users/*/collection/movies': 0
    '*.trakt.tv/users/*/collection/shows': 0
    '*.trakt.tv/users/*/ratings/*': 0
    '*.trakt.tv/users/*/watched/movies': 0
    '*.trakt.tv/users/*/watchlist/movies': 0
    '*.trakt.tv/users/*/watchlist/shows': 0
    '*.trakt.tv/users/likes/lists': 0
    '*.trakt.tv/users/me': 0

damon@hp-9470m:/mnt/drive1/backup$
```

### Version

0.25.0

### Python Version

Python 3.8.10

### Operating System and Version

Linux hp-9470m 5.4.0-135-generic #152-Ubuntu SMP Wed Nov 23 20:19:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
