### ISSUE TITLE
Can't set PGID to existing Group Id. (Code Change suggested).

### ISSUE THREAD

**Issue by Alan111S** [Taxel/PlexTraktSync#1291]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists
- [X] I have tried downgrading to find version that can be used as a workaround

### The problem

The recent changes for [Switch user only if needed (configured via PUID/PGID)](https://github.com/Taxel/PlexTraktSync/commit/d2439daa7b7f754d7e0634c6f688067a3cf875a1) have caused an issue for me running on Synology NAS.

This recently added code in entrypoint.sh tries to switch the id of the plextraktsync group to PGID set in the docker compose file:-

`if [ -n "$gid" ] && [ "$(id -g $APP_GROUP)" != "$gid" ]; then 
      groupmod -g "$gid" "$APP_GROUP"
fi`

On Synology NAS, it's convenient to set PGID=100 which is the id of the "users" group, but the issue is the docker file already contains a group with id=100 so I get an error:-

`groupmod: GID '100' already exists`

If you could change the command to perform `groupmod -o -g "$gid" "$APP_GROUP"` then we could use a non-unique group id.

I've had a look at some other docker images I use and having duplicate group ids doesn't seem to cause an issue.

### Error trace / logs

```text
groupmod: GID '100' already exists
```

### Expected behavior

plextraktsync is failing to start due to the error:-

groupmod: GID '100' already exists

when I set PGID: 100 in my docker-compose file.

I expect that the value of PGID should not matter regardless of whether that group id number has been used in the docker image or not.

### Steps to reproduce the behavior

This is my docker-compose file:-

```
# PlexTraktSync - https://github.com/Taxel/PlexTraktSync
# <mkdir -p /volume1/docker/mediarr/ptsync>
  ptsync:
    container_name: ptsync
    image: ghcr.io/taxel/plextraktsync:latest
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
    depends_on:
      - plex
    restart: unless-stopped
    network_mode: bridge
    command: watch
    environment:
      - PUID=1026
      - PGID=100
      - UMASK=002
      - TZ=Australia/Melbourne
      - PYTHON_VERSION=3.1
    volumes:
      - /volume1/docker/ptsync:/app/config:rw
```

If I set PGID to 100 (users group on Synology), I get the issue. To workaround the problem I can set PGID to 1000.

### Workarounds

The workaround is to set PGID to 1000 in the docker compose file

### Install method

docker-compose

### Version

PlexTraktSync 0.25.0

### Python Version

Python 3.11.1

### Operating System and Version

Synology DSM 7.1.1-42962
