### ISSUE TITLE
Feature request: Fetch servers before syncing

### ISSUE THREAD

**Issue by chaptergy** [Taxel/PlexTraktSync#1414]
### Use case

In case, the IP address of a Plex Media Server is not static, the URL of it changes as well (because it contains the IP). An example snippet from the servers.yml might look like this:

```yml
my-plex-server:
    token: d9th-onA5iug93-bLxuQ1s
    urls:
    - https://123-123-123-123.jxrdwhywbaxb0urov6ek8beud9hn1821.plex.direct:10482
    - http://123.123.123.123:10482
```
So whenever the IP address changes, the syncing fails, and instead you have to delete the server.yml and login to Plex again. It would be cool if it could automatically fetch the servers before a sync and update them if necessary. Or if there was a command to update the servers.

### Workarounds

Just having a static IP address, I guess

### Plan to implement

Not right now, I could look into it in the future, but so far I don't know anything about the Plex API
