### ISSUE TITLE
AlertListener Error: [Errno -3]

### ISSUE THREAD

**Issue by Alan111S** [Taxel/PlexTraktSync#1561]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists
- [ ] I have tried downgrading to find version that can be used as a workaround

### The problem

SInce a couple of days ago, I've been getting this issue in my logs. I've tried logging in to Plex and Trakt again but that hasn't resolved the issue. I run the app in Docker with command 'watch'.

I also run a cronjob to execute sync as a separate command every 15 minutes and that is working fine.

### Error trace / logs

```text
INFO     Starting AlertListener:                                                
         wss://192-168-50-200.5f356be8e49849d8b5d78804596182d2.plex.direct:32400
         /:/websockets/notifications?X-Plex-Token=<hidden>                      
ERROR    AlertListener Error: [Errno -3] Try again                              
ERROR    [Errno -3] Try again - goodbye                                         
ERROR    Server closed connection                                               
ERROR    Listener finished. Restarting in 15 seconds
```

### Expected behavior

No errors should be shown

### Steps to reproduce the behavior

docker exec -it ptsync /bin/sh

Then

plextraktsync watch

### Inspect of problematic items

```text
None
```

### Workarounds

None

### Install method

docker-compose

### Config file contents

```yaml
# Config File: /app/config/config.yml
cache:
  path: /app/config/trakt_cache
excluded-libraries:
- Demos
- MKV Kids
- MKV Yasmin
- Music
- Photo
- Video
config:
  dotenv_override: true
plex:
  timeout: 30
logging:
  append: true
  console_time: false
  debug: true
  filename: plextraktsync.log
  filter_loggers: null
  filter: null
sync:
  plex_to_trakt:
    collection: true
    clear_collected: false
    ratings: false
    watched_status: false
    watchlist: true
  trakt_to_plex:
    liked_lists: true
    ratings: false
    watched_status: true
    watchlist: false
    watchlist_as_playlist: false
  rating_priority: plex
watch:
  add_collection: false
  remove_collection: false
  scrobble_threshold: 90
  username_filter: true
  media_progressbar: true
xbmc-providers:
  movies: imdb
  shows: tvdb
```

### Version

0.26.11

### Python Version

3.11.4

### Operating System and Version

Linux
