### ISSUE TITLE
PlexTraktSync is broken for Plex 2FA users

### ISSUE THREAD

**Issue by ericswpark** [Taxel/PlexTraktSync#1584]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists
- [ ] I have tried downgrading to find version that can be used as a workaround

### The problem

Trying to run PTS for the first time and I'm getting a 401 unauthorized error when signing in.

### Error trace / logs

```text
> plextraktsync sync
INFO     PlexTraktSync [0.27.4]
Please enter your Plex username or e-mail (ericswpark): ericswpark
If you have 2 Factor Authentication enabled on Plex you can append the code
to your password below (eg. passwordCODE)
Please enter your Plex password:
Log in to Plex failed: '(401) unauthorized;
https://plex.tv/api/v2/users/signin <?xml version="1.0" encoding="UTF-8"?>
<errors>   <error code="1029" message="Please enter the verification code"
status="401"/> </errors> ', Try again.
```

### Expected behavior

Logging in to Plex works

### Steps to reproduce the behavior

1. Run `plextraktsync sync`
2. Type in username
3. Type in password with TOTP code

### Install method

pipx

### Config file contents

```yaml
# Config File: /Users/ericswpark/Library/Application Support/PlexTraktSync/config.yml
cache:
  path: /Users/ericswpark/Library/Caches/PlexTraktSync/trakt_cache
excluded-libraries:
- Private
- Family Holidays
config:
  dotenv_override: true
plex:
  timeout: 30
logging:
  append: true
  console_time: false
  debug: false
  filename: plextraktsync.log
  filter_loggers: null
  filter: null
sync:
  plex_to_trakt:
    collection: true
    clear_collected: false
    ratings: true
    watched_status: true
    watchlist: true
  trakt_to_plex:
    liked_lists: true
    ratings: true
    watched_status: true
    watchlist: true
    watchlist_as_playlist: false
  rating_priority: plex
watch:
  add_collection: false
  remove_collection: false
  scrobble_threshold: 80
  username_filter: true
  media_progressbar: true
xbmc-providers:
  movies: imdb
  shows: tvdb
```

### Version

PlexTraktSync 0.27.4

### Python Version

3.11.5

### Operating System and Version

macOS 13.5.2
