### ISSUE TITLE
[CI] Version 0.27.8 and 0.27.9 docker images failed to build

### ISSUE THREAD

**Issue by foux** [Taxel/PlexTraktSync#1605]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists
- [X] I have tried downgrading to find version that can be used as a workaround

### The problem

Hi there,
Last tagged version of PlexTraktSync is v0.27.9, but the docker packages haven't been build for v0.27.8 and v0.27.9, is that expected?

Thanks!

### Error trace / logs

```text
N/A
```

### Expected behavior

A tag 0.27.9 should be available on docker, and latest should point to 0.27.9

### Steps to reproduce the behavior

1. Docker pull ghcr.io/taxel/plextraktsync:latest
2. Image pulled is v0.27.7 instead of version 0.27.9

Or : 
1. Docker pull ghcr.io/taxel/plextraktsync:0.27.9
2. Image doesn't existst, so can't pull

### Install method

docker-compose

### Config file contents

```yaml
# Config File: /app/config/config.yml
cache:
  path: /app/config/trakt_cache
excluded-libraries:
- Tests audios
- Enregistement séries
- Enregistrements Film
config:
  dotenv_override: true
plex:
  timeout: 30
logging:
  append: true
  console_time: true
  debug: false
  filename: plextraktsync.log
  filter_loggers: null
  filter: null
sync:
  plex_to_trakt:
    collection: false
    clear_collected: false
    ratings: true
    watched_status: true
    watchlist: false
  trakt_to_plex:
    liked_lists: false
    ratings: true
    watched_status: true
    watchlist: false
    watchlist_as_playlist: false
  rating_priority: plex
watch:
  add_collection: false
  remove_collection: false
  scrobble_threshold: 80
  username_filter: true
  media_progressbar: false
xbmc-providers:
  movies: imdb
  shows: tvdb
```

### Version

0.27.9

### Python Version

N/A

### Operating System and Version

Docker
