### ISSUE TITLE
Watched time mismatch

### ISSUE THREAD

**Issue by pargnyce** [Taxel/PlexTraktSync#1765]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists
- [X] I have tried downgrading to find version that can be used as a workaround

### The problem

The sync command works but the time is mismatched (8 hours difference vs. Plex Media Server Watched time)

### Steps to reproduce the behavior

plextraktsync sync

### Expected behavior

It should sync but time will not match the plex media server

### Install method

pipx

### Config file contents

```yaml
cache:
  path: C:\Users\user\AppData\Local\PlexTraktSync\PlexTraktSync\Cache/trakt_cache
excluded-libraries:
- Private
- Family Holidays
config:
  dotenv_override: true
plex:
  timeout: 30
logging:
  append: true
  console_time: false
  debug: false
  filename: plextraktsync.log
  filter_loggers: null
  filter: null
sync:
  plex_to_trakt:
    collection: false
    clear_collected: false
    ratings: false
    watched_status: true
    watchlist: false
  trakt_to_plex:
    liked_lists: false
    ratings: false
    watched_status: true
    watchlist: false
    watchlist_as_playlist: false
  rating_priority: plex
watch:
  add_collection: false
  remove_collection: false
  scrobble_threshold: 80
  username_filter: true
  media_progressbar: true
xbmc-providers:
  movies: imdb
  shows: tvdb
```

### Version

0.27.5

### Python Version

3.10.11

### Plex Server Version

1.32.8.7639

### Operating System and Version

Windows-10

https://github.com/Taxel/PlexTraktSync/discussions/1741
