### ISSUE TITLE
Unable to setup the container

### ISSUE THREAD

**Issue by apriliars3** [Taxel/PlexTraktSync#1766]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists
- [X] I have tried downgrading to find version that can be used as a workaround

### The problem

Once the container is started, it always restarts before the command can be configured and entered "plextraktsync login".

### Steps to reproduce the behavior

Use the docker compose and start the container. it´s not possible to setup because restart always.

### Expected behavior

I think need fix it

### Install method

docker-compose

### Config file contents

```yaml
version: '2'
services:
  plextraktsync:
    image: ghcr.io/taxel/plextraktsync
    command: sync
    container_name: plextraktsync
    restart: on-failure:2
    volumes:
      - ./config:/app/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Tallinn
```

### Version

0.25.17

### Python Version

3.10.11

### Plex Server Version

1.32.8.7639

### Operating System and Version

DSM 7.2.1

**Comment by glensc** [comment]
Unsure what are you trying to do and what is happening. share the transcript of the session.  The exact command what you run and what output do you get. Details matter.

**Comment by Shayne55434** [comment]
@apriliars3 ,

I was in your exact spot. The only way I could get it to work was to set it up outside of a Docker container and then copy the following files to `./config`:

- .env
- .pytrakt.json
- config.yml
- servers.yml

Here's my docker compose file, which utilizes its own .env file:
```yaml
version: "3.8"
services:
  plex-trakt-sync:
    hostname: "plex-trakt-sync"
    container_name: "plex-trakt-sync"
    environment:
      - "PGID=${ID}"
      - "PUID=${ID}"
      - "TZ=${TZ}"
    command: sync
    image: "ghcr.io/taxel/plextraktsync"
    restart: "${RESTARTAPP}"
    networks:
      - ${DOCKERNETWORK}
    security_opt:
      - "${SECURITYOPS}:${SECURITYOPSSET}"
    volumes:
      - "${APPFOLDER}/plex-trakt-sync/config:/app/config"
    labels:
      - "dockupdater.enable=true"
networks:
  proxy:
    driver: bridge
    external: true
```

Hope this helps!
