### ISSUE TITLE
Repeatedly Downloading Trakt List, Nothing Else Happens

### ISSUE THREAD

**Issue by mocharilla** [Taxel/PlexTraktSync#1788]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists
- [X] I have tried downgrading to find version that can be used as a workaround

### The problem

Sync was working perfectly fine until I updated in the last few days. Now, instead of updating anything, it just keeps repeatedly saying "INFO Downloaded Trakt list" with a set of playlists that repeat over and over. I tried unliking those playlists to see if they specifically were the problem, but it just gave me the errors with different playlists. At no point does it ever do anything else until it eventually gives a completed sync message. It does not give an error at any point.

<img width="850" alt="Screenshot 2024-02-04 at 8 53 31 PM" src="https://github.com/Taxel/PlexTraktSync/assets/158978688/06b34a03-ef27-48d7-9e4d-9223a16be961">

 
<img width="1397" alt="Screenshot 2024-02-04 at 8 56 22 PM" src="https://github.com/Taxel/PlexTraktSync/assets/158978688/79cbd1d7-7c40-44ea-8be7-6ef5f5dcdbd7">

### Steps to reproduce the behavior

1. plextraktsync sync
This persists despite computer restarts, reinstalls of plextraktsync, and downgrading to the last working version.

### Expected behavior

Syncing of the watched status between Trakt and Plex. I added new files since the last sync which are marked as watched in Trakt and properly formatted on the server. This behavior has worked perfectly fine before I updated most recently.

### Workarounds

I tried downgrading, but it did not fix the issue. The version that was working was 27.10 before updating, but the issue persists when downgrading back to that.

### Install method

pipx

### Config file contents

<details>

```yaml
cache:
  path: $PTS_CACHE_DIR/trakt_cache

excluded-libraries:
  - Disney
  - Broadway

config:
  dotenv_override: true

plex:
  timeout: 30

logging:
  append: true
  # Whether to show timestamps in console messages
  console_time: false
  debug: false
  filename: plextraktsync.log
  # Additional logger names to apply filtering
  filter_loggers:
#    - plexapi
#    - requests_cache.backends
#    - requests_cache.backends.base
#    - requests_cache.backends.sqlite
#    - requests_cache.policy.actions
#    - requests_cache.session
#    - trakt.core
#    - urllib3.connectionpool
  filter:
#    # Filter out all messages with level WARNING
#    - level: WARNING
#    # Filter out message with level WARNING and containing a text
#    - level: WARNING
#      message: "not found on Trakt"
#    - message: "because provider local has no external Id"
#    - message: "because provider none has no external Id"
#    - message: "Retry using search for specific Plex Episode"
#    # Filter out messages by requests_cache
#    - name: requests_cache.backends
#    - name: requests_cache.backends.base
#    - name: requests_cache.backends.sqlite
#    - name: requests_cache.policy.actions
#    - name: requests_cache.session

# settings for 'sync' command (default)
sync:
  plex_to_trakt:
    collection: false
    # Clear collected state of items not present in Plex
    clear_collected: true
    ratings: false
    watched_status: false
    # If plex_to_trakt watchlist=false and trakt_to_plex watchlist=true
    # the Plex watchlist will be overwritten by Trakt watchlist
    watchlist: false
  trakt_to_plex:
    liked_lists: true
    ratings: true
    watched_status: true
    # If trakt_to_plex watchlist=false and plex_to_trakt watchlist=true
    # the Trakt watchlist will be overwritten by Plex watchlist
    watchlist: true
    # If you prefer to fetch trakt watchlist as a playlist instead of
    # plex watchlist, toggle this to true (is read only if watchlist=true)
    watchlist_as_playlist: true
  # Setting for whether ratings from one platform should have priority.
  # Valid values are trakt, plex or none. (default: plex)
  # none - No rating priority. Existing ratings are not overwritten.
  # trakt - Trakt ratings have priority. Existing Plex ratings are overwritten.
  # plex - Plex ratings have priority. Existing Trakt ratings are overwritten.
  rating_priority: trakt

# settings for 'watch' command
watch:
  add_collection: false
  remove_collection: false
  # what video watched percentage (0 to 100) triggers the watched status
  scrobble_threshold: 90
  # true to scrobble only what's watched by you, false for all your PMS users
  username_filter: true
  # Show the progress bar of played media in terminal
  media_progressbar: true

xbmc-providers:
  movies: imdb
  shows: tvdb

##### Advanced settings below this line, don't edit unless you know what you're doing #####
#http_cache:
  # https://requests-cache.readthedocs.io/en/main/user_guide/expiration.html#url-patterns
  # https://requests-cache.readthedocs.io/en/main/user_guide/expiration.html#expiration-values
  #
  # The value is seconds to cache.
  # Or one of the following special values:
  # - DO_NOT_CACHE: Skip both reading from and writing to the cache
  # - EXPIRE_IMMEDIATELY: Consider the response already expired, but potentially usable
  # - NEVER_EXPIRE: Store responses indefinitely
  #
  # The value can be also suffixed with a time unit:
  # - 5m, 1h, 3d
  # See full documentation at:
  # - https://github.com/wroberts/pytimeparse#pytimeparse-time-expression-parser
  #
  # NOTE: If there is more than one match, the first match will be used in the order they are defined
#  policy:
#    "*.trakt.tv/users/me": 1d
#    "*.trakt.tv/users/likes/lists": DO_NOT_CACHE

# vim:ts=2:sw=2:et
```

</details>

### Version

0.28.15

### Python Version

3.12.1

### Plex Server Version

1.40.0.7775-456fbaf97

### Operating System and Version

macOS Sonoma 14.1
