### ISSUE TITLE
Watchlist is syncing both ways, but config is set for only one-way sync

### ISSUE THREAD

**Issue by profucius** [Taxel/PlexTraktSync#1872]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists
- [ ] I have tried downgrading to find version that can be used as a workaround

### The problem

When using `PlexTraktSync sync` command, the script fully syncs my watchlist on Plex to Trakt, and also my watchlist on Trakt to Plex. However, it should _not_ be syncing the latter, due to how I have my config.yml set.

### Steps to reproduce the behavior

1. Set config.yml
2. Run plextraktsync sync
3. Watch the command output as it syncs both watchlists.
4. Check Plex and see the added items.

### Expected behavior

The watchlist should sync any items in the Plex Watchlist to the Trakt Watchlist, but not sync the other way around.

### Workarounds

My current workaround is to use another python script to delete all items from the Plex Watchlist. I do this because I want all items in my Trakt Watchlist only, and my Plex Watchlist to be empty.

### Config file contents

```yaml
cache:
  path: $PTS_CACHE_DIR/trakt_cache
excluded-libraries:
- Private
log_debug_messages: false
logging:
  append: false
  console_time: true
  filename: plextraktsync.log
sync:
  plex_to_trakt:
    collection: true
    ratings: false
    watched_status: true
    watchlist: true
  trakt_to_plex:
    liked_lists: false
    ratings: true
    watched_status: true
    watchlist: true
watch:
  add_collection: true
  scrobble_threshold: 80
  username_filter: true
xbmc-providers:
  movies: imdb
  shows: tvdb
```

### Install method

pipx

### Version

0.29.8

### Python Version

 3.11.0

### Plex Server Version

1.40.0.7998

### Operating System and Version

Windows 11 22H2

**Comment by profucius** [comment]
I have updated my original post. Below are more details about what I am requesting here.

If this is a feature request instead, then please consider this:

The config terminology "watchlist" may need to be changed to be more specific to the functionality. I look at the config file and see watchlist=true and I think "It will copy items in this direction" whereas what it actually does is "It will copy AND delete to make a mirror in this direction".

Perhaps a solution to this could be something like:

```yaml
plex_to_trakt:
  watchlist_master: false
  watchlist_mirror: false
trakt_to_plex:
  watchlist_master: true
  watchlist_mirror: false
```

The functionality that I'm requesting is: If "watchlist" is set to true, it will copy in a direction but NOT mirror (aka, not delete from either side). And if set to false, then do not copy at all.

In plain language, I want to be able to copy Watchlist items from Plex to Trakt, but not copy watch list items from Trakt to Plex. The end result would be Plex always moves items into tract, so that tracked is the master list, and tracked does not copy back into Plex again.

The reason I am requesting for this is because I use another script that reads both my Plex and Trakt watchlists, and if they both have the same items (aka traditional sync), Then it becomes a duplication nightmare. When I tried to remove an item from one, I have to always remember to remove it from both, otherwise PlexTraktSync we'll just recopy the deleted item from one back over to the other again.

I hope this makes sense. I'm happy to rephrase or elaborate if needed.

**Comment by glensc** [comment]
These open issues relate in some sense:
- https://github.com/Taxel/PlexTraktSync/issues/1494
- https://github.com/Taxel/PlexTraktSync/issues/1080
- https://github.com/Taxel/PlexTraktSync/issues/1247

**Comment by glensc** [comment]
Current logic of watchlist sync is here:
- https://github.com/Taxel/PlexTraktSync/blob/1584207cf5316e5cfab8ef3ef77427f88775d769/plextraktsync/sync/Sync.py#L196-L231

**Comment by glensc** [comment]
Personally, I want this flow from playlist syncing:

1. use plex watchlist, not plex playlist (`watchlist_as_playlist: false`)
1. keep plex and trakt in sync (both `watchlist: true`)
2. remove played items from the playlists (not yet supported)
3. do not re-add items to playlist if they have been watched. not sure how to handle re-watches (not yet supported)

**Comment by JeanGionet** [comment]
if both plex and trakt are set to watchlist  = true .... shouldn't the script MIRROR those watchlists to they match exactly? (same watchlist on both sides)

`
sync:
  plex_to_trakt:

    watchlist: true
  trakt_to_plex:

    watchlist: true
`
Right now I have both watchlists set to true. But, for whatever reason, if I delete something from my PLEX watchlist, it doesn't remove it from my Trakt watchlist. The script simply RE-ADDS what I just removed in PLEX since it's still listed on my Trakt watchlist. But, if I delete something from my TRAKT watchlist, the script will remove it from my PLEX watchlist.

**Comment by glensc** [comment]
@JeanGionet please see already reported issues list from here:
- https://github.com/Taxel/PlexTraktSync/issues/1872#issuecomment-2016419279

there's no state stored for PlexTraktSync for it to know it if item was missing on one list, or you removed it.

**Comment by dimikal37** [comment]
Is there any update on this? 

It would be nice if we could choose if we want to to append the content from a Plex watchlist to a Trakt watchlist and vice versa. 
Rather than mirroring the entire content.

Currently it can be done only if you set both settings in True but in my case that it is not desired.
```
  plex_to_trakt:
    watchlist: true

  trakt_to_plex:
    watchlist: true
```

What I am looking is to have this option when you have one of the below settings:
```
  plex_to_trakt:
    watchlist: true

  trakt_to_plex:
    watchlist: false
```
OR

```
  plex_to_trakt:
    watchlist: false

  trakt_to_plex:
    watchlist: true
```
