### ISSUE TITLE
Watchlist not syncing

### ISSUE THREAD

**Issue by EnSt0rm** [Taxel/PlexTraktSync#1940]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists
- [ ] I have tried downgrading to find version that can be used as a workaround

### The problem

I run the sync command, and my collection and watched status updates properly, but my Plex Watchlist will not sync across to my Trakt Watchlist or vice-versa.
I've checked my config file and `plex_to_trakt` has `watchlist: true`, and `trakt_to_plex` also has `watchlist: true`.
I've tried `watchlist_as_playlist: false` and `true`, doesn't seem to make any difference.

### Steps to reproduce the behavior

docker-compose run --rm plextraktsync sync

### Expected behavior

Watchlist to be synced between Plex universal watchlist, and Trakt watchlist

### Config file contents

```yaml
cache:
  path: /app/config/trakt_cache
excluded-libraries:
- Private
- Family Holidays
config:
  dotenv_override: true
plex:
  timeout: 30
logging:
  append: true
  console_time: false
  debug: false
  filename: plextraktsync.log
  filter_loggers: null
  filter: null
sync:
  rating_priority: plex
  plex_to_trakt:
    collection: true
    clear_collected: false
    ratings: true
    watched_status: true
    watchlist: true
  trakt_to_plex:
    liked_lists: true
    ratings: true
    watched_status: true
    watchlist: true
    watchlist_as_playlist: false
    playback_status: false
watch:
  add_collection: false
  remove_collection: false
  scrobble_threshold: 80
  username_filter: true
  media_progressbar: true
  ignore_clients: null
xbmc-providers:
  movies: imdb
  shows: tvdb
```

### Install method

docker-compose

### Version

0.30.4

### Python Version

3.12.3

### Plex Server Version

1.40.2.8395

### Operating System and Version

Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with
