### ISSUE TITLE
Watch Service No Longer Working On Debian Linux

### ISSUE THREAD

**Issue by paterson37** [Taxel/PlexTraktSync#2102]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists
- [ ] I have tried downgrading to find version that can be used as a workaround

### The problem

Since setting this up in September it's been working perfectly via the watch service.

However, as of 20th November, it stopped tracking. I had not made any changes to anything on my system. So I am unsure what the problem could be.

When I check sudo systemctl status PlexTraktSync.service I get the below output.

```
● PlexTraktSync.service - PlexTraktSync watch daemon
     Loaded: loaded (/etc/systemd/system/PlexTraktSync.service; enabled; preset>
     Active: activating (auto-restart) (Result: exit-code) since Mon 2024-11-25>
   Main PID: 1999259 (code=exited, status=203/EXEC)
        CPU: 1ms
```

I hadn't ran an update command in a while so I thought I would try updating but that hasn't fixed it either.

My service file is as below.
```

[Unit]
Description=PlexTraktSync watch daemon
After=network-online.target

[Service]
ExecStart=plextraktsync watch
Restart=on-failure
RestartSec=10

[Install]
WantedBy=multi-user.target
```

Apologies, I am still new when it comes to the like of linux and such things.

### Steps to reproduce the behavior

1. sudo systemctl status PlexTraktSync.service
2. Checked output 
```
● PlexTraktSync.service - PlexTraktSync watch daemon
     Loaded: loaded (/etc/systemd/system/PlexTraktSync.service; enabled; preset>
     Active: activating (auto-restart) (Result: exit-code) since Mon 2024-11-25>
   Main PID: 1999259 (code=exited, status=203/EXEC)
        CPU: 1ms 
```

3. Tried replacing ExecStart string with path as per the readme page on here and doing the daemon, service start and service enable commands. But status showed same thing.

### Expected behavior

Service to run watch command in background and scrobble what I'm watching on Plex.

### Config file contents

```yaml
# Config File: /home/craig/.config/PlexTraktSync/config.yml
cache:
  path: /home/craig/.cache/PlexTraktSync/trakt_cache
excluded-libraries:
- Anime
- Anime - Movies
- Foreign - Movies
- Foreign - Series
- Fan Edits
config:
  dotenv_override: true
plex:
  timeout: 30
logging:
  append: true
  console_time: false
  debug: false
  filename: plextraktsync.log
  filter_loggers: null
  filter: null
sync:
  rating_priority: plex
  plex_to_trakt:
    collection: false
    clear_collected: false
    ratings: false
    watched_status: true
    watchlist: true
  trakt_to_plex:
    liked_lists: true
    ratings: false
    watched_status: true
    watchlist: true
    watchlist_as_playlist: false
    playback_status: false
liked_lists:
  keep_watched: true
watch:
  add_collection: false
  remove_collection: false
  scrobble_threshold: 80
  username_filter: true
  media_progressbar: true
  ignore_clients: null
xbmc-providers:
  movies: imdb
  shows: tvdb
```

### Install method

pipx

### Version

0.32.2

### Python Version

3.11.2

### Plex Server Version

1.41.1.9057-af5eaea7a

### Operating System and Version

Debian GNU/Linux 12 bookworm (x86-64), Cinnamon 5.6.8
