### ISSUE TITLE
Plextraktsync hangs while syncing

### ISSUE THREAD

**Issue by U1F984** [Taxel/PlexTraktSync#2107]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if identical issue already exists
- [ ] I have tried downgrading to find version that can be used as a workaround

### The problem

The sync process stops. No more CPU is consumed. This happens randomly (I'd estimate 2/3s of the time, the other 1/3 it runs without issue).

I'm attempting to get a stacktrace of what the process is doing using `PYTHONFAULTHANDLER=1` and will report back when I have such a stacktrace.

### Steps to reproduce the behavior

1. Install crontab entry to run `docker compose run --rm plextraktsync` daily
2. Wait for 1-2 weeks
3. Observe stuck processes

### Error trace / logs

```text
Here's the relevant containers:

root        1933  0.0  0.3 1237940 8044 ?        Sl   Nov29   6:58 /usr/bin/containerd-shim-runc-v2 -namespace moby -id d9f7c686d9396012dc858bfcffe1abc3f7278d747b94c79e1a539dbd798a36e
1000        1954  0.0 13.1 294344 275500 ?       Ssl  Nov29 160:54  \_ python -m plextraktsync sync
root        2618  0.0  0.3 1238196 8060 ?        Sl   Nov30   6:11 /usr/bin/containerd-shim-runc-v2 -namespace moby -id 4c183f15c85e30b82f6ad1340414e8c98c92642157a9468ea5c89b4a3c4afca
1000        2640  0.0  2.7  73332 56824 ?        Ssl  Nov30 117:23  \_ python -m plextraktsync sync
root        7299  0.0  0.3 1238196 8284 ?        Sl   Dec07   1:17 /usr/bin/containerd-shim-runc-v2 -namespace moby -id 018d97d2c456cc9f1cde7bacbe1dc679704b3d8b49b53dfe2be134a2155f23a
1000        7319  0.0 21.8 478428 458764 ?       Ssl  Dec07  70:38  \_ python -m plextraktsync sync
root        7950  0.0  0.4 1238196 10100 ?       Sl   Dec08   0:44 /usr/bin/containerd-shim-runc-v2 -namespace moby -id 322f664b7cba8bee7ad92b5718571351a4e4636eaa24233970dc4534f71aa34
1000        7971  0.0 10.9 242876 230112 ?       Ssl  Dec08  24:40  \_ python -m plextraktsync sync

Sample log ending (different containers have different endings):

[...]
INFO     Preloaded shows data (12067 shows)                                     
INFO     Preload shows matches                                                  
WARNING  9/11 - Animal Squad | Pen & Paper (2017): Skipping                     
         <PlexGuid:tvdb://326417> not found on Trakt
```

### Expected behavior

Sync takes some time and then finishes.

### Workarounds

I'm also now executing it with `timeout 22h docker compose run ...` so that the containers will stop accumulating.

### Config file contents

```yaml
cache:
  path: /app/config/trakt_cache
excluded-libraries:
- Private
- Family Holidays
config:
  dotenv_override: true
plex:
  timeout: 30
logging:
  append: true
  console_time: false
  debug: false
  filename: plextraktsync.log
  filter_loggers: null
  filter: null
sync:
  rating_priority: plex
  plex_to_trakt:
    collection: true
    clear_collected: false
    ratings: true
    watched_status: true
    watchlist: true
  trakt_to_plex:
    liked_lists: true
    ratings: true
    watched_status: true
    watchlist: true
    watchlist_as_playlist: false
    playback_status: false
liked_lists:
  keep_watched: true
watch:
  add_collection: false
  remove_collection: false
  scrobble_threshold: 80
  username_filter: true
  media_progressbar: true
  ignore_clients: null
xbmc-providers:
  movies: imdb
  shows: tvdb
```

### Install method

docker-compose

### Version

0.32.2

### Python Version

3.13.0

### Plex Server Version

1.41.2.9200

### Operating System and Version

Linux-6.8.8-3-pve-x86_64-with
