### ISSUE TITLE
Cant schedule using ofelia because of "No such container: plextraktsync"

### ISSUE THREAD

**Issue by SebbeJohansson** [Taxel/PlexTraktSync#2139]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if an identical issue or discussion already exists
- [X] I have tried downgrading to find version that can be used as a workaround

### The problem

Running ofelia with the suggested settings and setup is not working.
```
administrator@big-vault:~$ sudo docker-compose logs scheduler
2025-01-05T00:18:00.017Z  common.go:121 ▶ ERROR [Job "plextraktsync" (df74273cad1b)] Finished in "963.091µs", failed: true, skipped: false, error: No such container: plextraktsync
```

### Steps to reproduce the behavior

1. Setup PlexTraktSync according to the documentation.
2. Setup ofelia according to the documentation.
3. Start the containers using `sudo docker-compose up -d` or `sudo docker compose up -d`.
4. Wait for the schedule to run.
5. Check the logs.

### Error trace / logs

```text
administrator@big-vault:~$ sudo docker-compose logs scheduler
2025-01-05T00:18:00.016Z  common.go:125 ▶ NOTICE [Job "plextraktsync" (df74273cad1b)] Started - --server 'The Big Vault Movies' sync
2025-01-05T00:18:00.017Z  common.go:121 ▶ ERROR [Job "plextraktsync" (df74273cad1b)] Finished in "963.091µs", failed: true, skipped: false, error: No such container: plextraktsync
```

### Expected behavior

I expect the scheduled job to run.

### Config file contents

```yaml
plextraktsync:
    image: ghcr.io/taxel/plextraktsync
    command: sync
    container_name: plextraktsync
    profiles: ["schedule"]
    volumes:
      - /configs/mediarr/plextraktsync:/app/config
    environment:
      - PUID=1000
      - PGID=1000
    depends_on:
      - plex
  scheduler:
    image: mcuadros/ofelia:latest
    container_name: scheduler
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.job-run.plextraktsync.schedule: "0 6,18 * * *"
      ofelia.job-run.plextraktsync.container: "plextraktsync"
      ofelia.job-run.plextraktsync.command: "--server 'The Big Vault Movies' sync"
      ofelia.job-run.plextraktsync2.schedule: "0 12,0 * * *"
      ofelia.job-run.plextraktsync2.container: "plextraktsync"
      ofelia.job-run.plextraktsync2.command: "--server 'The Big Vault TV Shows' sync"
```

### Install method

docker-compose

### Version

0.32.7

### Python Version

3.13.1

### Plex Server Version

4.16.0

### Operating System and Version

Ubuntu 20.04
