### ISSUE TITLE
Watch (Scrobbling) for Managed User Only

### ISSUE THREAD

**Issue by RenewedKeys** [Taxel/PlexTraktSync#2147]
### Confirmation

- [X] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [X] I have checked if an identical issue or discussion already exists
- [ ] I have tried downgrading to find version that can be used as a workaround

### The problem

Got it up and running well but experiencing an issue where watch will scrobble for not just my managed user but also the Plex Main Account User.

My Plex setup is as follows: 

- Main Account User (scrobbles but do NOT want)
   - Managed User 1 (scrobbles as desired)
   - Managed User 2 (no scrobbling)
   - Managed User 3 (no scrobbling)

### Steps to reproduce the behavior

1. Complete first run and log into Plex and Trakt.
2. Select Server
3. Select Managed User.
4. Run plextractsync command: watch and test on Trakt.tv to see what scrobbles.

### Expected behavior

Unless I am misunderstand how it is supposed to work, I desire that trakt scrobbling only works for Managed User 1, not the Primary Plex account user.

### Config file contents

```yaml
cache:
  path: $PTS_CACHE_DIR/trakt_cache
  - Private
  - Family Holidays
config:
  dotenv_override: true
plex:
  timeout: 300
logging:
  append: true
  console_time: false
  debug: false
  filename: plextraktsync.log
  filter_loggers:
  filter:
sync:
  rating_priority: plex
  plex_to_trakt:
    collection: false
    clear_collected: false
    ratings: false
    watched_status: true
    watchlist: false
  trakt_to_plex:
    liked_lists: false
    ratings: true
    watched_status: true
    watchlist: true
    watchlist_as_playlist: false
    playback_status: false
liked_lists:
watch:
  add_collection: false
  remove_collection: false
  scrobble_threshold: 80
  username_filter: true
  media_progressbar: true
  ignore_clients: ~
xbmc-providers:
  movies: imdb
  shows: tvdb
```

### Install method

docker-compose

### Version

0.32.7

### Python Version

3.13.1

### Plex Server Version

1.41.3.9314

### Operating System and Version

Windows 11
