### ISSUE TITLE
API didn't respond properly, script will abort now

### ISSUE THREAD

**Issue by blazer380** [Taxel/PlexTraktSync#2177]
### Confirmation

- [x] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [x] I have checked if an identical issue or discussion already exists
- [ ] I have tried downgrading to find version that can be used as a workaround

### The problem

ERROR    Got exception while working on <plextraktsync.queue.TraktBatchWorker.TraktBatchWorker object at
         0x000001EC772AD8D0>: API didn't respond properly, script will abort now. Please try again later.
WARNING  Bad Response - Response could not be parsed for plextraktsync.queue.TraktBatchWorker.add_to_collection(),
         retrying after 1 seconds (try: 1/5)

[plextraktsync.log](https://github.com/user-attachments/files/18647854/plextraktsync.log)

### Steps to reproduce the behavior

1. Installed from scratch the latest version for Windows (PlexTraktSync-0.34.1)
2. Ran the setup.bat
3. Ran plextraktsync.bat

### Error trace / logs

```text
ERROR    Got exception while working on <plextraktsync.queue.TraktBatchWorker.TraktBatchWorker object at
         0x000001EC772AD8D0>: API didn't respond properly, script will abort now. Please try again later.
WARNING  Bad Response - Response could not be parsed for plextraktsync.queue.TraktBatchWorker.add_to_collection(),
         retrying after 1 seconds (try: 1/5)
```

### Expected behavior

No new items since last proper sync (December 30th) have been added to the trakt.tv site for my account.

### Inspect of problematic items

```text

```

### Config file contents

```yaml
cache:
  path: $PTS_CACHE_DIR/trakt_cache

# You may want to use per server libraries config instead:
# - https://github.com/Taxel/PlexTraktSync#libraries
excluded-libraries:
  - Private
  - Family Holidays

config:
  dotenv_override: true

plex:
  timeout: 30

logging:
  append: true
  # Whether to show timestamps in console messages
  console_time: false
  debug: true
  filename: plextraktsync.log
  # Additional logger names to apply filtering
  filter_loggers:
  #    - plexapi
  #    - requests_cache.backends
  #    - requests_cache.backends.base
  #    - requests_cache.backends.sqlite
  #    - requests_cache.policy.actions
  #    - requests_cache.session
  #    - trakt.core
  #    - urllib3.connectionpool
  filter:
#    # Filter out all messages with level WARNING
#    - level: WARNING
#    # Filter out message with level WARNING and containing a text
#    - level: WARNING
#      message: "not found on Trakt"
#    - message: "because provider local has no external Id"
#    - message: "because provider none has no external Id"
#    - message: "Retry using search for specific Plex Episode"
#    # Filter out messages by requests_cache
#    - name: requests_cache.backends
#    - name: requests_cache.backends.base
#    - name: requests_cache.backends.sqlite
#    - name: requests_cache.policy.actions
#    - name: requests_cache.session

# settings for 'sync' command
sync:
  # Setting for whether ratings from one platform should have priority.
  # Valid values are trakt, plex or none. (default: plex)
  # none - No rating priority. Existing ratings are not overwritten.
  # trakt - Trakt ratings have priority. Existing Plex ratings are overwritten.
  # plex - Plex ratings have priority. Existing Trakt ratings are overwritten.
  rating_priority: plex

  plex_to_trakt:
    collection: true
    # Clear collected state of items not present in Plex
    clear_collected: false
    ratings: true
    watched_status: true
    # If plex_to_trakt watchlist=false and trakt_to_plex watchlist=true
    # the Plex watchlist will be overwritten by Trakt watchlist
    watchlist: true
  trakt_to_plex:
    liked_lists: true
    ratings: true
    watched_status: true
    # If trakt_to_plex watchlist=false and plex_to_trakt watchlist=true
    # the Trakt watchlist will be overwritten by Plex watchlist
    watchlist: true
    # If you prefer to fetch trakt watchlist as a playlist instead of
    # plex watchlist, toggle this to true (is read only if watchlist=true)
    watchlist_as_playlist: false
    # Sync Play Progress from Trakt to Plex
    playback_status: false

# Configuration for liked lists
liked_lists:
  # Whether to keep watched items in the list
  keep_watched: true

# Configuration override for specific lists
#liked_list:
#  "Saw Collection":
#    keep_watched: true

# settings for 'watch' command
watch:
  add_collection: false
  remove_collection: false
  # what video watched percentage (0 to 100) triggers the watched status
  scrobble_threshold: 80
  # true to scrobble only what's watched by you, false for all your PMS users
  username_filter: true
  # Show the progress bar of played media in terminal
  media_progressbar: true
  # Clients to ignore when listening Play events
  ignore_clients: ~

xbmc-providers:
  movies: imdb
  shows: tvdb
##### Advanced settings below this line, don't edit unless you know what you're doing #####
#http_cache:
# https://requests-cache.readthedocs.io/en/main/user_guide/expiration.html#url-patterns
# https://requests-cache.readthedocs.io/en/main/user_guide/expiration.html#expiration-values
#
# The value is seconds to cache.
# Or one of the following special values:
# - DO_NOT_CACHE: Skip both reading from and writing to the cache
# - EXPIRE_IMMEDIATELY: Consider the response already expired, but potentially usable
# - NEVER_EXPIRE: Store responses indefinitely
#
# The value can be also suffixed with a time unit:
# - 5m, 1h, 3d
# See full documentation at:
# - https://github.com/wroberts/pytimeparse#pytimeparse-time-expression-parser
#
# NOTE: If there is more than one match, the first match will be used in the order they are defined
#  policy:
#    "*.trakt.tv/users/me": 1d
#    "*.trakt.tv/users/likes/lists": DO_NOT_CACHE

# vim:ts=2:sw=2:et
```

### Install method

zip download (not supported)

### Version

0.34.0dev0

### Python Version

3.10.11

### Plex Server Version

1.41.3.9314-a0bfb8370

### Operating System and Version

Windows 10 Pro
