### ISSUE TITLE
New plex device notification spam

### ISSUE THREAD

**Issue by qcoomer** [Taxel/PlexTraktSync#2206]
### Confirmation

- [x] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [x] I have checked if an identical issue or discussion already exists
- [x] I have tried downgrading to find version that can be used as a workaround

### The problem

I have updated to version 0.34.5 and no everytime plextraktsync runs, i receive a new device to access plex notification.
Is this the new expected behaviour?

![Image](https://github.com/user-attachments/assets/724317fd-ce76-4958-a0dc-b88cee1f1b58)

### Steps to reproduce the behavior

install and setup plextraktsync 

### Error trace / logs

```text

```

### Expected behavior

not spam notifications on every run.

### Inspect of problematic items

```text

```

### Config file contents

```yaml

```

### Install method

docker-compose

### Version

0.34.5

### Python Version

3.13.2

### Plex Server Version

1.41.4.9463

### Operating System and Version

Windows 11; running plextraktsync in docker

**Comment by sasagr** [comment]
It is happening to me as well. Any fix?

**Comment by glensc** [comment]
Can anyone contact trakt support and ask what has changed? you can link to this thread and give feedback what they replied.

**Comment by simonc56** [comment]
I'm not sure but a workaround would be to set a `PLEXAPI_HEADER_IDENTIFIER` environment variable to prevent plexapi to randomize it at every run.

@sasagr @qcoomer Can you try it ?

Example in compose.yml :
```yaml
services:
  plextraktsync:
    image: ghcr.io/taxel/plextraktsync
    command: sync
    container_name: plextraktsync
    volumes:
      - ./config:/app/config
    environment:
      - PUID=1000
      - PGID=1000
      - PLEXAPI_HEADER_IDENTIFIER=johndoe
```
