### ISSUE TITLE
Relogin overwrites custom server configuration

### ISSUE THREAD

**Issue by miracle152004** [Taxel/PlexTraktSync#2222]
### Confirmation

- [x] I have read the [README.md](https://github.com/Taxel/PlexTraktSync#readme) on the project homepage
- [x] I have checked if an identical issue or discussion already exists
- [x] I have tried downgrading to find version that can be used as a workaround

### The problem

If I have to relogin into the plex server because the token is no longer valid, the custom server configuration gets overwritten.

### Steps to reproduce the behavior

1. Login into server
2. create custom config with the libraries that should be synced
3. check config
4. relogin into server
5. check login again.

### Error trace / logs

```text
-
```

### Expected behavior

Only the token should be updated.

### Inspect of problematic items

```text
-
```

### Workarounds

No known workaround

### Config file contents

```yaml
cache:
  path: /home/christopher/.cache/PlexTraktSync/trakt_cache
excluded-libraries:
- Private
- Family Holidays
config:
  dotenv_override: true
plex:
  timeout: 30
logging:
  append: true
  console_time: false
  debug: false
  filename: plextraktsync.log
  filter_loggers: null
  filter: null
sync:
  rating_priority: plex
  plex_to_trakt:
    collection: false
    clear_collected: false
    ratings: false
    watched_status: false
    watchlist: false
  trakt_to_plex:
    liked_lists: true
    ratings: true
    watched_status: true
    watchlist: true
    watchlist_as_playlist: false
    playback_status: false
liked_lists:
  keep_watched: true
watch:
  add_collection: false
  remove_collection: false
  scrobble_threshold: 80
  username_filter: true
  media_progressbar: true
  ignore_clients: null
xbmc-providers:
  movies: imdb
  shows: tvdb
```

### Install method

pipx

### Version

0.34.2

### Python Version

3.10.12

### Plex Server Version

1.41.5.9522

### Operating System and Version

Linux-5.15.0-134-generic-x86_64-with-glibc2.35
