### ISSUE TITLE
First start Docker

### ISSUE THREAD

**Issue by FloydKulis** [Taxel/PlexTraktSync#364]
I would like to run PlexTraktSync from docker. This is because after every Synology update, I have to reinstall PIP3.

Would you tell me how to do the first docker installation to add credentials for Trakt?

Using the manual:

> To run the container: docker start -ia ptsync
> 
> The first run must be interactive (docker run -
> it or docker start -ia) in order to setup your trakt and plex credentials.

![image](https://user-images.githubusercontent.com/37215675/123760138-dabbe700-d8c0-11eb-8052-896fb6218718.png)

**Comment by glensc** [comment]
what manual? this project does not have any of such info.

also, you need to use latest version to report bugs.

**Comment by FloydKulis** [comment]
Sorry, I still can't handle this forum.
I can see that the docker I used is not an "official" solution. I didn't know where to ask the question.
I used this docker:
https://hub.docker.com/r/twolaw/plextraktsync

When you try to start it for the first time, it immediately gets STOP.
Can any of you use Docker of your super script?

**Comment by glensc** [comment]
that's a fork of this project.

**Comment by KaHooli** [comment]
For @FloydKulis , I've been trying to use this as a docker image as well for some time now, and this is how I got it to work...

1. Run the following to get a command prompt within the running container...
```bash
docker run -it --name plextraktsync-name --network t2_proxy --entrypoint="/bin/sh" kahooli/plextraktsync
```
_"kahooli/plextraktsync" is a duplicate copy of this repo, that automatically update the docker hub image after being updated._

2. Keep running ```python3 main.py``` from /app directory until Trakt syncs with Plex
3. Copy the contents of the following files to external files of the same name under a unique directory _(eg under ~/docker/appdata/plextraktsync-name/)_
- .env
- .pytrakt.json
- config.json
4. Stop container and remove it
5. Configure under docker compose file the following...
```yaml
  plextraktsync-name:
    image: kahooli/plextraktsync
    container_name: plextraktsync-name
    networks:
      - t2_proxy
    volumes:
      - /home/username/appdata/plextraktsync-name/.env:/app/.env
      - /home/username/appdata/plextraktsync-name/.pytrakt.json:/app/.pytrakt.json
      - /home/username/appdata/plextraktsync-name/config.json:/app/config.json
    entrypoint: ["python3", "main.py", "watch"]
```
