### ISSUE TITLE
Feature request: official docker repository

### ISSUE THREAD

**Issue by xonvanetta** [Taxel/PlexTraktSync#411]
### Feature description

Having an official docker repository with the build tags ready to be used.   

### Use case

Instead of having to install python and all the requirements we could just use it in a container and run it without needing to install it. A benefit to this is that if someone is saying they are using docker with tag X it easier to troubleshoot than to guess what python version they are using and if the installation was correct. 

### Workarounds

https://hub.docker.com/r/kahooli/plextraktsync
Not up to date, also not using tags which i am no fan of.  

### Plan to implement

I could try but i am not fluent in python with what is best practices for running code in containers.
There was a Dockerfile if its ready to use would only need to configure github to push finished image to a repository, and some docs so it would be easy to understand

**Comment by Scales82** [comment]
yes I would 100% love to have this. a docker compose with it would be great, my containers would automatically update also

**Comment by glensc** [comment]
The Dockerfile already exists here, someone needs to provide a docker compose and GitHub action to build and push docker images.

**Comment by glensc** [comment]
ps: python version and incorrect installation is rarely the source of problems :)

**Comment by chrillep** [comment]
only issue would be owner of the docker hub repo 😊.


https://docs.github.com/en/actions/guides/publishing-docker-images#publishing-images-to-docker-hub-and-github-packages

**Comment by rfgamaral** [comment]
> 
> 
> only issue would be owner of the docker hub repo 😊.
> 
> [docs.github.com/en/actions/guides/publishing-docker-images#publishing-images-to-docker-hub-and-github-packages](https://docs.github.com/en/actions/guides/publishing-docker-images#publishing-images-to-docker-hub-and-github-packages)

It should be published to ghcr.io instead.

**Comment by KaHooli** [comment]
While I've kept my duplicate GitHub repository current, the auto build feature on Docker Hub is no longer free, so it isn't keeping my repo up to date.

I'm looking into GitHub Actions for publishing to ghcr for my own education, but I agree it would be better if done on the official GitHub repo.

**Comment by glensc** [comment]
Well, this issue is exactly for that. submit your PRs!

- https://github.com/Taxel/PlexTraktSync/issues/411#issuecomment-890745171

**Comment by glensc** [comment]
Docker images are published now:
- https://github.com/Taxel/PlexTraktSync/pull/413
- https://github.com/Taxel/PlexTraktSync/pull/423

This should be documented now.

also, docker compose config should be added and such invocation be preferred.

**Comment by iFredOS** [comment]
Hi. Where is the documentation/instructions for the configuration?

**Comment by glensc** [comment]
@iFredOS nobody has made them. therefore the issue is still open.

**Comment by iFredOS** [comment]
> @iFredOS nobody has made them. therefore the issue is still open.

Ah ok, I understand.

**Comment by glensc** [comment]
@iFredOS everyone is welcome to contribute!

The documentation should end up in README.md

**Comment by chrillep** [comment]
> > @iFredOS nobody has made them. therefore the issue is still open.
> 
> Ah ok, I understand.

i haven't had time to through it but it should probably be something like the #docker part in https://hub.docker.com/r/twolaw/plextraktsync#docker

feel free to try that and document if possible 😊

**Comment by Scales82** [comment]
I would love to help, but Im not knowledgeable enough.
I only run a docker-compose stack that I just copy-paste from other people. So if we can have an appropriate YML for that as well, I'd be forever grateful.

**Comment by blckwhtx** [comment]
services:
  plextraktsync:
    image: ghcr.io/taxel/plextraktsync:main
    container_name: plextraktsync
    network_mode: host
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - plextraktsync:/app      !!! This folder "app/main.py" is not found, normally the folders are created and the files are created there. or something is missing
    command: > 
      "python""-m""plex_trakt_sync"    <--- do I need this here too?


in any case tried everything possible, it breaks off at "app / main.py", does not find a directory

**Comment by glensc** [comment]
Merged:
- https://github.com/Taxel/PlexTraktSync/pull/458

Community contributions are welcome to actually document all of this!

**Comment by KaHooli** [comment]
In case it helps with someone creating the documentation, this is my compose file entries for the containers...
```yaml
plextraktsync-name1:
    image: ghcr.io/taxel/plextraktsync:latest
    container_name: plextraktsync-name1
    networks:
      - t2_proxy
    depends_on:
      - plex
    restart: unless-stopped
    volumes:
      - $DOCKERDIR/appdata/plextraktsync-name1/.env:/app/.env
      - $DOCKERDIR/appdata/plextraktsync-name1/.pytrakt.json:/app/.pytrakt.json
      - $DOCKERDIR/appdata/plextraktsync-name1/config.json:/app/config.json
    entrypoint: ["python3", "main.py", "watch"]

  plextraktsync-name2:
    image: ghcr.io/taxel/plextraktsync:latest
    container_name: plextraktsync-name2
    networks:
      - t2_proxy
    depends_on:
      - plex
    restart: unless-stopped
    volumes:
      - $DOCKERDIR/appdata/plextraktsync-name2/.env:/app/.env
      - $DOCKERDIR/appdata/plextraktsync-name2/.pytrakt.json:/app/.pytrakt.json
      - $DOCKERDIR/appdata/plextraktsync-name2/config.json:/app/config.json
    entrypoint: ["python3", "main.py", "watch"]
```
