### ISSUE TITLE
Marked as watched too early

### ISSUE THREAD

**Issue by agneevX** [Taxel/PlexTraktSync#530]
### The problem

An episode was watched 81%, and a routine cron job marked it was watched on both on Plex and Trakt.

### Expected behavior

Don't mark as watched until its watched 95% (or until Plex deems it as watched).

### Steps to reproduce the behavior

_With a complete code example, if possible_

### Workarounds

_Is there an existing workaround for this issue?_

### Environment

- Version: 0.15.0
- Python version: 3.10.0
- Platform: Docker

**Comment by twolaw** [comment]
Can you provide logs please.
The script does not mark as watched on both Plex and Trakt by itself.
It compares watch status between Plex and Trakt to make it equal.

**Comment by agneevX** [comment]
> Can you provide logs please.

This happened last night as 10. Noticed this today morning, sadly erased, by the `watch` command or some other command execution.

> Do you use watch command too or just sync ?

I use `watch` command as a daemon, while `sync` runs as a cron job.

`0 22 * * * ping -qc 5 1.1.1.1 && docker run --rm -u "1001:1001" -e "TZ=Asia/Kolkata" -v /opt/appdata/plextraktsync:/app/config --name pts-sync ghcr.io/taxel/plextraktsync sync --no-progress-bar > /dev/null 2>&1`

```yml
version: "3.9"
services:
  plextraktsync:
    container_name: plextraktsync
    image: ghcr.io/taxel/plextraktsync
    restart: unless-stopped
    user: "1001:1001"
    command: "watch"
    healthcheck:
      test: ["CMD", "wget", "-nv", "-t1", "--spider", "10.0.0.11:32400/identity"]
    logging: 
      driver: none
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - /opt/appdata/plextraktsync:/app/config
    labels:
      - "org.hotio.pullio.update=true"
      - "org.hotio.pullio.notify=true"
      - "org.hotio.pullio.discord.webhook=${DISCORD_WEBHOOK}"
```
