### ISSUE TITLE
Feature request: Correction to example docker compose with Ofelia

### ISSUE THREAD

**Issue by Droppisalt** [Taxel/PlexTraktSync#952]
This docker compose needs "-" before to list each Ofelia labels.
```
services:
  scheduler:
    image: mcuadros/ofelia:latest
    container_name: scheduler
    depends_on:
      - plextraktsync
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.job-run.plextraktsync.schedule="@every 6h"
      ofelia.job-run.plextraktsync.container="plextraktsync"
  plextraktsync:
    image: ghcr.io/taxel/plextraktsync:latest
    container_name: plextraktsync
    volumes:
      - ./config:/app/config
```
to:
```
services:
  scheduler:
    image: mcuadros/ofelia:latest
    container_name: scheduler
    depends_on:
      - plextraktsync
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - ofelia.job-run.plextraktsync.schedule="@every 6h"
      - ofelia.job-run.plextraktsync.container="plextraktsync"
  plextraktsync:
    image: ghcr.io/taxel/plextraktsync:latest
    container_name: plextraktsync
    volumes:
      - ./config:/app/config
```

**Comment by glensc** [comment]
Send pull request

**Comment by glensc** [comment]
also difficult to read the changes, use diff syntax and code fence markdown:

```
```diff
 unchanged line
-old line
+new line
 unchanged line
```
```

**Comment by twolaw** [comment]
No `-` needed, the fix is `:` instead of `=` :

```diff
labels:
-  ofelia.job-run.plextraktsync.schedule="@every 6h"
-  ofelia.job-run.plextraktsync.container="plextraktsync"
+  ofelia.job-run.plextraktsync.schedule: "@every 6h"
+  ofelia.job-run.plextraktsync.container: "plextraktsync"
```

source: https://docs.docker.com/compose/compose-file/compose-file-v3/

**Comment by glensc** [comment]
Yeah, there are two syntaxes, both are valid if used properly, pay attention to dash and colon and equal sign.

```yml
build:
  labels:
    com.example.description: "Accounting webapp"
    com.example.department: "Finance"
    com.example.label-with-empty-value: ""

```

```yml
build:
  labels:
    - "com.example.description=Accounting webapp"
    - "com.example.department=Finance"
    - "com.example.label-with-empty-value"
```
